//시작번호는 1, 증가치는 1, 최대값은 2인 s_seq 시퀀스를 생성
CREATE SEQUENCE s_seq
INCREMENT BY 1
START WITH 1
MAXVALUE 100;

SELECT min_value, max_value, increment_by, last_number
FROM user_sequences
WHERE sequence_name = 'S_SEQ';

INSERT INTO emp (empno, ename, job, deptno)
VALUES(S_SEQ.NEXTVAL, 'CANDY', 'SALESMAN', 20);

INSERT INTO emp (empno, ename, job, deptno)
VALUES(S_SEQ.NEXTVAL, 'CANDY10', 'SALESMAN', 20);

INSERT INTO emp (empno, ename, job, deptno)
VALUES(S_SEQ.NEXTVAL, 'CANDY20', 'SALESMAN', 20);

SELECT * FROM emp;

SELECT S_SEQ.CURRVAL 
FROM dual;

SELECT S_SEQ.NEXTVAL
FROM dual;

//시퀀스 정의 변경
ALTER SEQUENCE S_SEQ MAXVALUE 200;

//시퀀스 삭제
DROP sequence S_SEQ;

//AUTO_INCREMENT와 비슷한 IDENTITY 기능, 내부적으로는 오라클의 sequence를 자동 생성 사용함.
CREATE TABLE member(id NUMBER GENERATED BY DEFAULT AS IDENTITY, name VARCHAR2(100));

INSERT INTO member(name)
VALUES('홍길동');

INSERT INTO member(name)
VALUES('홍길순');

SELECT * FROM member;

//연락처 정보를 저장하기 위한 주소록(address)테이블을 생성
CREATE TABLE address
(id NUMBER(3), name VARCHAR2(50), addr VARCHAR2(100), phone VARCHAR2(30), 
 email VARCHAR2(100));

SELECT * FROM tab;
desc address;

//서브쿼리를 이용한 예제 데이터 입력
INSERT INTO address
VALUES(1, 'HGDONG', 'SEOUL', '123-456', 'gdhon@cwunet.ac.kr');

COMMIT;

SELECT * FROM address;

//서브쿼리절을 이용하여 주소록 테이블의 구조와 데이터를 복사하여 addr_second 테이블을 생성
CREATE TABLE addr_second(id, name, addr, phone, email)
AS SELECT * FROM address;

desc addr_second;

//주소록테이블에서 id, name 칼럼만 복사하여 addr_fourth 테이블을 생성
//단, 데이터는 복사하지 않는다
CREATE TABLE addr_fourth
AS SELECT id, name FROM address
WHERE 1=2;

desc addr_fourth;

//주소록테이블에서 id, name 칼럼만 복사하여 addr_third 테이블을 생성
CREATE TABLE addr_third
AS SELECT id, name FROM address;

desc addr_third;

SELECT * FROM addr_third;

//주소록 테이블에 날짜타입을 가지는 birth 칼럼을 추가
ALTER TABLE address
ADD (birth DATE);

DESC address;

//주소록 테이블에 문자타입을 가지는 comment 칼럼을 추가
//기본값은‘No Comment’로지정
ALTER TABLE address
ADD (comments VARCHAR2(200) DEFAULT 'NO COMMENT');

DESC address;

INSERT INTO address (id, name, addr)
VALUES(2, 'hr', '서울');

//주소록 테이블에서 comment 칼럼을 삭제
ALTER TABLE address DROP COLUMN comments;

desc address;

//주소록 테이블에서 phone 칼럼의 데이터타입의 크기를 50으로 증가
ALTER TABLE address
MODIFY phone VARCHAR2(50);

desc address;

//addr_second 테이블 이름을 client_address로 변경
RENAME addr_second to client_address;

SELECT * FROM tab;

//addr_third 테이블을 삭제
DROP TABLE addr_third;

SELECT * FROM tab
WHERE tname = 'ADD_THIRD';

//client_address 테이블의 데이터와 할당된 공간을 삭제
TRUNCATE TABLE client_address;

SELECT * FROM client_address;

ROLLBACK;

SELECT * FROM client_address;

//주소록 테이블에서 ‘고객 주소록 관리하기 위한 테이블’이라는 주석을 추가
COMMENT ON TABLE address
IS '고객 주소록을 관리하기 위한 테이블';

//주소록 테이블의 name 칼럼에 ‘고객 이름’이라는 주석을 추가
COMMENT ON TABLE address
IS '고객 이름';

//테이블주석확인하는 방법
SELECT comments
FROM user_tab_comments
WHERE table_name = 'ADDRESS';

//칼럼주석확인하는 방법
COMMENT on column address.name is '고객 이름';

SELECT *
FROM user_col_comments
WHERE table_name = 'ADDRESS';

//칼럼주석 삭제
COMMENT on column address.name is '';

SELECT *
FROM user_col_comments
WHERE table_name = 'ADDRESS';

//USER_ 데이터 사전 뷰 조회
SELECT table_name FROM user_tables;

//ALL_ 데이터 사전 뷰 조회
SELECT owner, table_name FROM all_tables;

//DBA_ 데이터 사전 뷰 조회
SELECT owner, table_name FROM dba_tables;

//테이블 이름이 ADDR로 시작하는 테이블의 이름, 테이블이저장된 테이블 스페이스 이름, 
//최소 확장 영역수와 최대 확장 영역수를 출력
SELECT table_name, tablespace_name, min_extents, max_extents
FROM user_tables
WHERE table_name LIKE 'ADD%';

//객체의 종류가 테이블이고 이름이 ADDR로 시작하는 객체의 이름, 종류, 생성날짜를 출력
SELECT  object_name, object_type, created
FROM user_objects
WHERE object_name LIKE 'ADD%' AND object_type ='TABLE';

//USER_CATALO 사용
SELECT * FROM user_catalog;

//무결성 제약조건 생성
CREATE TABLESPACE indxx
datafile 'C:\app\kosa\product\21c\oradata\XE\indxx.dbf' size 100m;

CREATE TABLE subject
 (subno NUMBER(5)
  CONSTRAINT subject_no_pk PRIMARY KEY
  DEFERRABLE INITIALLY DEFERRED
  USING INDEX TABLESPACE indxx,
  subname VARCHAR2(20)
  CONSTRAINT subject_name_nn NOT NULL,
  term VARCHAR2(1)
  CONSTRAINT subject_term_ck CHECK (term in('1', '2')),
  type VARCHAR2(6));

desc subject;

SELECT * FROM student;
DELETE FROM student
WHERE studno = 33333;
//중복값 삭제

//무결성 제약조건 생성
ALTER TABLE student
ADD CONSTRAINT stud_no_pk primary key(studno);

//수강(sugang) 테이블 인스턴스
CREATE TABLE sugang
  (studno NUMBER(5)
   CONSTRAINT sugang_studno_fk REFERENCES student(studno),
   subno number(5)
   CONSTRAINT sugang_subno_fk REFERENCES subject(subno),
   regdate DATE,
   result NUMBER(3),
   CONSTRAINT sugang_fk PRIMARY KEY(studno, subno));

//USER_CONSTRAINTS 데이터 사전에서 무결성 제약조건 조회
SELECT constraint_name, constraint_type
FROM user_constraints
WHERE table_name IN ('SUBJECT', 'SUGANG');

//학생 테이블인 스턴스를 참조하여 studno에 기본키, idnum에 고유키,name에 NOT NULL 무결성 제약조건을 추가
ALTER TABLE student
ADD CONSTRAINT stud_idum_uk UNIQUE(idnum);

ALTER TABLE student
MODIFY (name CONSTRAINT stud_name_nn NOT NULL);

ALTER TABLE department
ADD CONSTRAINT stud_deptno_fk primary key(deptno);

ALTER TABLE student ADD CONSTRAINT stud_deptno1_fk
FOREIGN KEY(deptno) REFERENCES department(deptno);

//p44의 부서테이블 인스턴스를 참조하여 deptno에 기본키, dname에 NOT NULL 무결성 제약조건을 추가
ALTER TABLE department 
MODIFY (dname not null);

//p44의 교수테이블 인스턴스를 참조하여 profno에 기본키, name에 NOT NULL, deptno에 
//참조 무결성 제약조건을 추가
ALTER TABLE professor 
ADD CONSTRAINT prof_pk primary key(profno);

ALTER TABLE professor 
MODIFY (name not null);

ALTER TABLE professor 
ADD CONSTRAINT prof_fk 
FOREIGN KEY(deptno) REFERENCES department(deptno);

//강좌테이블에서 무결성 제약조건에 위반되는 데이터의 예를 입력
INSERT INTO subject VALUES(1,'SQL', '1', '필수');

INSERT INTO subject VALUES (2, ' ', '2', '필수');

INSERT INTO subject VALUES (3, 'JAVA', '3', '선택');

COMMIT;

SELECT * FROM subject;

//강좌테이블의무결성제약조건(subject_id_pk)에위반되는데이터를입력하여오류메시지를확인
INSERT INTO subject VALUES(4,'데이터 베이스', '1', '필수');

INSERT INTO subject VALUES(4,'데이터 베이스', '2', '선택');

COMMIT;

SELECT * FROM subject;

//강좌테이블의 subject_pk_ck 무결성 제약조건을 삭제
SELECT constraint_name, constraint_type 
FROM user_constraintS
WHERE table_name = 'SUBJECT';

ALTER TABLE subject
DROP CONSTRAINT subject_term_ck;

SELECT constraint_name, constraint_type 
FROM user_constraintS
WHERE table_name = 'SUBJECT';

//수강테이블의 sugang_studno_fk 무결성 제약조건을 비활성화
ALTER TABLE sugang
DISABLE CONSTRAINT sugang_fk;

SELECT constraint_name, constraint_type 
FROM user_constraintS
WHERE table_name in ('SUBJECT', 'sugang');

//수강테이블의 dugang_studno_fk 무결성 제약조건을 활성화
ALTER TABLE sugang
ENABLE CONSTRAINT sugang_fk;

SELECT constraint_name, status
FROM user_constraintS
WHERE table_name = 'SUGANG';

//student, professor, department 테이블에 정의된 모든 종류의 무결성 제약조건을 조회
SELECT constraint_name, constraint_type, status
FROM user_constraintS
WHERE table_name IN ('STUDENT', 'PROFESSOR', 'DEPARTMENT');

//제약조건이 설정된 칼럼 이름을 저장
SELECT table_name, column_name, constraint_name
FROM user_cons_columns
WHERE table_name in ('STUDENT', 'PROFESSOR', 'DEPARTMENT');

//아래와 같이 EMPLOYEE 테이블을 생성
//( EMPLOYEE_ID는 자동 증가, PRIMARY KEY, NAME는 NOT NULL)

--Name Null Type
-------- ------------- ------------
--EMPLOYEE_ID NUMBER(7)
--NAME VARCHAR2(25)
--ADDRESS VARCHAR2(25)
--DEPTNO NUMBER(2)
--PHONE_NUMBER VARCHAR2(20)


CREATE TABLE EMPLOYEE
   (EMPLOYEE_ID NUMBER(7) PRIMARY KEY,
    NAME VARCHAR2(25) NOT NULL,
    ADDRESS VARCHAR2(25),
    DEPTNO NUMBER(2),
    PHONE_NUMBER VARCHAR2(20));
    
CREATE SEQUENCE EMPLOYEE_SEQ
START WITH 1
INCREMENT BY 1;

//위에서 생성한 테이블에 아래와 같이 4건의 데이터를 입력
INSERT INTO EMPLOYEE
VALUES (EMPLOYEE_SEQ.NEXTVAL, '고구마', 'pho@naver.com', 40,'010-1234-5678');

INSERT INTO EMPLOYEE
VALUES (EMPLOYEE_SEQ.NEXTVAL, '사이다', 'soda@naver.com', 40,'010-9101-1121');

INSERT INTO EMPLOYEE
VALUES (EMPLOYEE_SEQ.NEXTVAL, '필요해', 'need@naver.com', 40,'010-3141-5161');

INSERT INTO EMPLOYEE
VALUES (EMPLOYEE_SEQ.NEXTVAL, '집집집', 'house@naver.com', 40,'010-7181-9202');

//위에서 생성한 EMPLOYEE 테이블의 DEPTNO는 DEPT테이블의 DEPTNO 컬럼을 참조하게 제약 조건을 설정
ALTER TABLE EMPLOYEE
ADD CONSTRAINT EMPLOYEE_DEPTNO_FK
FOREIGN KEY (DEPTNO)
REFERENCES DEPT(DEPTNO);

//INSERT INTO employee(name, deptno)
//VALUES('BENJAMIN',50);
//데이터를 입력하려고 하였으나 실패하였다. 이유는?
--dept 테이블에 50번 부서가 존재하지 않기 때문에 입력불가

//생성한 EMPLOYEE 테이블을 삭제
DROP TABLE EMPLOYEE;