package project;

/** Administrator-only audit history screen. */
final class AdminLogsPage {
    private AdminLogsPage() {}

    static String render() {
        return "<!doctype html><html lang='ko'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>관리 로그 | CINEHUB</title>"
            + "<link rel='stylesheet' href='/static/assets/css/style.css'><link rel='stylesheet' href='/static/assets/css/widgets.css'><link rel='stylesheet' href='/static/assets/css/responsive.css'></head><body>"
            + "<header class='main-header header-style-1'><div class='header-top'></div><div class='header-sticky'><div class='container align-self-center'><div class='main-nav'><nav><ul class='main-menu'><li><a href='/'>홈</a></li><li><a href='/movies'>영화 추천</a></li><li><a href='/posts'>게시글</a></li><li><a href='/admin'>관리자</a></li></ul></nav></div></div></div></header>"
            + "<main><div class='container admin-log-page'><a class='board-back' href='/admin'>← 관리자 대시보드</a><div class='widget-header-3'><h1 class='widget-title'>관리 로그</h1></div><div class='admin-search'><input id='logQuery' placeholder='사용자, 작업, 대상, IP로 검색'><button id='logSearch'>검색</button></div>"
            + "<section class='log-section'><h2>관리자 작업 기록</h2><div class='log-table-wrap'><table class='audit-table'><thead><tr><th>시간</th><th>관리자</th><th>작업</th><th>대상</th><th>사유</th><th>IP</th></tr></thead><tbody id='actions'></tbody></table></div><nav class='pagination' id='actionPaging'></nav></section>"
            + "<section class='log-section'><h2>로그인 기록</h2><div class='log-table-wrap'><table class='audit-table'><thead><tr><th>시간</th><th>사용자</th><th>상태</th><th>IP</th></tr></thead><tbody id='logins'></tbody></table></div><nav class='pagination' id='loginPaging'></nav></section></div></main>"
            + "<footer class='main-footer'><div class='container'><p class='text-center text-muted'>CINEHUB · 영화 탐색 커뮤니티</p></div></footer>"
            + "<script>function safe(v){var d=document.createElement('div');d.textContent=v||'';return d.innerHTML;}var actions=[],logins=[],actionPage=0,loginPage=0;function pageButtons(id,page,pages,fn){document.getElementById(id).innerHTML=Array.from({length:pages},function(_,i){return '<button class=\"page-number '+(page===i?'active':'')+'\">'+(i+1)+'</button>';}).join('');Array.prototype.forEach.call(document.querySelectorAll('#'+id+' button'),function(b,i){b.onclick=function(){fn(i);};});}function filtered(a){var q=document.getElementById('logQuery').value.trim().toLowerCase();return q?a.filter(function(x){return Object.keys(x).some(function(k){return String(x[k]||'').toLowerCase().indexOf(q)>=0;});}):a;}function drawActions(){var a=filtered(actions),pages=Math.max(1,Math.ceil(a.length/10));if(actionPage>=pages)actionPage=0;document.getElementById('actions').innerHTML=a.slice(actionPage*10,actionPage*10+10).map(function(x){return '<tr><td>'+safe(x.createdAt)+'</td><td>'+safe(x.admin)+'</td><td>'+safe(x.action)+'</td><td>'+safe(x.targetType)+' #'+x.targetId+'</td><td>'+safe(x.reason)+'</td><td>'+safe(x.ip)+'</td></tr>';}).join('')||'<tr><td colspan=\"6\">검색 결과가 없습니다.</td></tr>';pageButtons('actionPaging',actionPage,pages,function(i){actionPage=i;drawActions();});}function drawLogins(){var a=filtered(logins),pages=Math.max(1,Math.ceil(a.length/10));if(loginPage>=pages)loginPage=0;document.getElementById('logins').innerHTML=a.slice(loginPage*10,loginPage*10+10).map(function(x){return '<tr><td>'+safe(x.createdAt)+'</td><td>'+safe(x.user)+'</td><td>'+safe(x.status)+'</td><td>'+safe(x.ip)+'</td></tr>';}).join('')||'<tr><td colspan=\"4\">검색 결과가 없습니다.</td></tr>';pageButtons('loginPaging',loginPage,pages,function(i){loginPage=i;drawLogins();});}function draw(){actionPage=0;loginPage=0;drawActions();drawLogins();}document.getElementById('logSearch').onclick=draw;document.getElementById('logQuery').addEventListener('keydown',function(e){if(e.key==='Enter')draw();});fetch('/api/admin/logs').then(function(r){if(!r.ok)throw 0;return r.json();}).then(function(d){actions=d.adminActions||[];logins=d.loginLogs||[];draw();}).catch(function(){location.href='/';});</script></body></html>";
    }
}
