package project;

/** Category page with a direct return and the same paging behavior as the full board list. */
final class CategoryBoardPage {
    private CategoryBoardPage() {}

    static String render(long boardId) {
        return "<!doctype html><html lang='ko'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>게시판 | CINEHUB</title>"
            + "<link rel='stylesheet' href='/static/assets/css/style.css'><link rel='stylesheet' href='/static/assets/css/widgets.css'><link rel='stylesheet' href='/static/assets/css/responsive.css'><link rel='stylesheet' href='/static/assets/css/post-layout.css'></head><body>"
            + "<header class='main-header header-style-1 font-heading'><div class='header-top'></div><div class='header-sticky'><div class='container align-self-center'><div class='main-nav'><nav><ul class='main-menu'><li><a href='/'>홈</a></li><li><a href='/movies'>영화 추천</a></li><li><a href='/about-us'>소개</a></li><li><a href='/posts'>게시글</a></li><li><a href='/mypage'>마이페이지</a></li></ul></nav></div><div class='header-tools'><ul class='list-inline'><li class='list-inline-item'><a href='/new-post'>글쓰기</a></li><li class='list-inline-item'><a href='/login'>로그인</a></li><li class='list-inline-item'><a href='/register'>회원가입</a></li></ul></div></div></div></header>"
            + "<main><div class='container'><a class='board-back' href='/posts'>← 전체 게시판</a><div class='widget-header-3'><h1 class='widget-title' id='boardTitle'>게시판</h1></div><nav class='pagination pagination-top' id='postPaginationTop'></nav><div id='posts'><p class='muted'>게시글을 불러오는 중입니다.</p></div><nav class='pagination' id='postPagination'></nav></div></main><footer class='main-footer'><div class='container'><p class='text-center text-muted'>CINEHUB · 영화 탐색 커뮤니티</p></div></footer>"
            + "<script>function safe(v){var d=document.createElement('div');d.textContent=v||'';return d.innerHTML;}var id=" + boardId + ";fetch('/api/boards').then(function(r){return r.json();}).then(function(d){var b=(d.boards||[]).filter(function(x){return x.id===id;})[0];if(b)document.getElementById('boardTitle').textContent=b.name;});fetch('/api/posts?boardId='+id).then(function(r){return r.json();}).then(function(d){var a=d.posts||[],page=1,draw=function(){var pages=Math.max(1,Math.ceil(a.length/10));document.getElementById('posts').innerHTML=a.slice((page-1)*10,page*10).map(function(p){return '<a class=\"post-card\" href=\"/post/'+p.id+'\"><h3>'+safe(p.title)+'</h3><p>'+safe(p.content).slice(0,100)+'</p><small>'+safe(p.author)+' · '+safe(p.createdAt)+'</small></a>';}).join('')||'<p class=\"muted\">이 게시판에는 아직 게시글이 없습니다.</p>';var controls=Array.from({length:pages},function(_,i){return '<button class=\"page-number '+(page===i+1?'active':'')+'\">'+(i+1)+'</button>';}).join('');document.getElementById('postPaginationTop').innerHTML=controls;document.getElementById('postPagination').innerHTML=controls;Array.prototype.forEach.call(document.querySelectorAll('#postPaginationTop button,#postPagination button'),function(b,i){b.onclick=function(){page=i%pages+1;draw();window.scrollTo({top:0,behavior:'smooth'});};});};draw();});</script></body></html>";
    }
}
