package project;

import com.sun.net.httpserver.HttpExchange;
import com.sun.net.httpserver.HttpServer;
import project.dao.PostDAO;
import project.dao.BoardDAO;
import project.dao.CommentDAO;
import project.dao.AdminDAO;
import project.dao.ReportDAO;
import project.dao.UserDAO;
import project.dto.Board;
import project.dto.Comment;
import project.dto.ReportDTO;
import project.dto.Post;
import project.dto.User;
import project.service.LoginResult;
import project.service.LoginService;
import project.common.DBConnection;
import project.security.PasswordHasher;
import java.io.IOException;
import java.net.InetSocketAddress;
import java.net.URLDecoder;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

/** Plain-Java HTTP server with the original Marcian Blog visual language and Oracle APIs. */
public final class CinehubServer {
    private final Map<String,User> sessions = new ConcurrentHashMap<>();
    private final Map<String,String> csrfTokens = new ConcurrentHashMap<>();
    private final UserDAO users = new UserDAO();
    private final PostDAO posts = new PostDAO();
    private final BoardDAO boards = new BoardDAO();
    private final CommentDAO comments = new CommentDAO();
    private final JavaRagService rag = new JavaRagService();
    private final OpenAiMovieAdvisor movieAdvisor = new OpenAiMovieAdvisor();
    private final AdminDAO admin = new AdminDAO();
    private final ReportDAO reports = new ReportDAO();

    public static void main(String[] args) throws IOException {
        int port=args.length==0?8080:Integer.parseInt(args[0]); CinehubServer app=new CinehubServer(); try{app.ensureAuditTables();}catch(Exception x){throw new IOException("audit table setup failed",x);}
        HttpServer server=HttpServer.create(new InetSocketAddress(port),0); server.createContext("/",app::route); server.setExecutor(java.util.concurrent.Executors.newCachedThreadPool()); server.start();
        System.out.println("CINEHUB Oracle server: http://127.0.0.1:"+port);
    }
    private void route(HttpExchange e) throws IOException {try {String path=e.getRequestURI().getPath();
        if(needsCsrf(e)&&!csrfValid(e)){json(e,403,"{\"error\":\"invalid csrf token\"}");return;}
        if("/api/health".equals(path)){json(e,200,"{\"database\":\"oracle\",\"status\":\"ok\"}");return;}
        if("/api/auth/register".equals(path)&&post(e)){register(e);return;} if("/api/auth/login".equals(path)&&post(e)){login(e);return;} if("/api/auth/logout".equals(path)&&post(e)){csrfTokens.remove(cookie(e));sessions.remove(cookie(e));json(e,204,"");return;}
        if("/api/posts".equals(path)&&get(e)){postList(e);return;} if("/api/posts".equals(path)&&post(e)){postCreate(e);return;} if(path.matches("/api/posts/\\d+/like")&&post(e)){postLike(e,id(path));return;} if(path.matches("/api/posts/\\d+")&&get(e)){postDetail(e,id(path));return;} if(path.matches("/api/posts/\\d+")&&put(e)){postUpdate(e,id(path));return;} if(path.matches("/api/posts/\\d+")&&delete(e)){postDelete(e,id(path));return;}
        if("/api/me".equals(path)&&get(e)){me(e);return;} if("/api/me".equals(path)&&delete(e)){withdraw(e);return;}
        if("/api/me/profile".equals(path)&&put(e)){profileUpdate(e);return;}
        if("/api/me/password".equals(path)&&put(e)){passwordUpdate(e);return;}
        if("/api/boards".equals(path)&&get(e)){boardList(e);return;}
        if("/api/boards".equals(path)&&post(e)){boardCreate(e);return;}
        if(path.matches("/api/boards/\\d+")&&put(e)){boardUpdate(e,id(path));return;}
        if(path.matches("/api/boards/\\d+")&&delete(e)){boardDelete(e,id(path));return;}
        if("/api/contact".equals(path)&&post(e)){contactCreate(e);return;}
        if("/api/movies/search".equals(path)&&get(e)){movieSearch(e);return;}
        if("/api/movies/random".equals(path)&&get(e)){movieRandom(e);return;}
        if("/api/movies/popular".equals(path)&&get(e)){moviePopular(e);return;}
        if(path.matches("/api/movies/\\d+")&&get(e)){movieDetail(e,id(path));return;}
        if("/api/my/posts".equals(path)&&get(e)){myPosts(e);return;}
        if("/api/notifications".equals(path)&&get(e)){notificationList(e);return;}
        if("/api/notifications/read".equals(path)&&put(e)){notificationRead(e);return;}
        if("/api/admin/stats".equals(path)&&get(e)){adminStats(e);return;}
        if("/api/admin/logs".equals(path)&&get(e)){adminLogs(e);return;}
        if("/api/admin/users".equals(path)&&get(e)){adminUsers(e);return;}
        if(path.matches("/api/admin/users/\\d+/status")&&put(e)){adminUserStatus(e,id(path));return;}
        if(path.matches("/api/admin/posts/\\d+/hide")&&put(e)){adminHidePost(e,id(path));return;}
        if("/api/reports".equals(path)&&post(e)){reportCreate(e);return;}
        if("/api/admin/reports".equals(path)&&get(e)){adminReports(e);return;}
        if(path.matches("/api/admin/reports/\\d+")&&put(e)){adminReportUpdate(e,id(path));return;}
        if(path.matches("/api/posts/\\d+/comments")&&get(e)){commentList(e,id(path));return;}
        if(path.matches("/api/posts/\\d+/comments")&&post(e)){commentCreate(e,id(path));return;}
        if("/".equals(path)&&get(e)){html(e,200,homePage());return;}
        if("/login".equals(path)&&get(e)){html(e,200,loginPage());return;}
        if("/register".equals(path)&&get(e)){html(e,200,registerPage());return;}
        if("/new-post".equals(path)&&get(e)){if(sessions.get(cookie(e))==null){redirect(e,"/login");return;}html(e,200,editorPage());return;}
        if("/posts".equals(path)&&get(e)){if(!loggedIn(e)){redirect(e,"/login");return;}html(e,200,BoardListPage.render());return;}
        if("/mypage".equals(path)&&get(e)){html(e,200,myPage());return;}
        if("/notifications".equals(path)&&get(e)){if(sessions.get(cookie(e))==null){redirect(e,"/login");return;}html(e,200,notificationsPage());return;}
        if("/admin/logs".equals(path)&&get(e)){if(!isAdmin(e)){redirect(e,"/");return;}html(e,200,AdminLogsPage.render());return;}
        if("/admin".equals(path)&&get(e)){if(!isAdmin(e)){redirect(e,"/");return;}html(e,200,AdminDashboardPage.render());return;}
        if(path.matches("/post/\\d+")&&get(e)){if(!loggedIn(e)){redirect(e,"/login");return;}html(e,200,detailPage(id(path)));return;}
        if("/about-us".equals(path)&&get(e)){html(e,200,infoPage("CINEHUB 소개","CINEHUB 소개","영화를 발견하고 감상과 추천을 나누는 영화 커뮤니티입니다."));return;}
        if("/contact-us".equals(path)&&get(e)){html(e,200,contactPage());return;}
        if("/movies".equals(path)&&get(e)){if(!loggedIn(e)){redirect(e,"/login");return;}html(e,200,moviesPage());return;}
        if(path.matches("/movies/\\d+")&&get(e)){if(!loggedIn(e)){redirect(e,"/login");return;}html(e,200,movieDetailPage(id(path)));return;}
        if("/page-search".equals(path)&&get(e)){html(e,200,searchPage());return;}
        if("/add-category".equals(path)&&get(e)){if(!isAdmin(e)){redirect(e,"/");return;}html(e,200,categoryManagePage());return;}
        if(path.matches("/category/\\d+")&&get(e)){if(!loggedIn(e)){redirect(e,"/login");return;}html(e,200,CategoryBoardPage.render(id(path)));return;}
        if(path.matches("/user/\\d+")&&get(e)){html(e,200,profilePage("사용자 게시글"));return;}
        if(path.matches("/user/\\d+/profile")&&get(e)){html(e,200,profilePage("사용자 프로필"));return;}
        if(path.matches("/user/\\d+/edit-profile")&&get(e)){html(e,200,profileEditPage());return;}
        if(path.matches("/user/\\d+/password-reset")&&get(e)){html(e,200,passwordPage());return;}
        if(path.matches("/edit-post/\\d+")&&get(e)){if(sessions.get(cookie(e))==null){redirect(e,"/login");return;}html(e,200,editPage(id(path)));return;}
        staticFile(e,path.substring(1));
    }catch(IllegalStateException x){json(e,"login required".equals(x.getMessage())?401:500,"{\"error\":\""+esc(x.getMessage())+"\"}");}catch(Exception x){json(e,500,"{\"error\":\""+esc(x.getMessage())+"\"}");}}
    private void register(HttpExchange e)throws Exception{Map<String,String> f=form(e);String id=req(f,"loginId"),password=req(f,"password"),nickname=req(f,"nickname"),email=req(f,"email");if(!id.matches("[A-Za-z0-9]{4,30}")||password.length()<8||password.length()>128){json(e,400,"{\"error\":\"invalid account format\"}");return;}if(users.isLoginIdDuplicate(id)||users.isNicknameDuplicate(nickname)){json(e,409,"{\"error\":\"duplicate account\"}");return;}if(!users.registerUser(new User(id,PasswordHasher.hash(password),nickname,email,"USER"))){json(e,400,"{\"error\":\"registration failed\"}");return;}json(e,201,"{\"created\":true}");}
    private void login(HttpExchange e)throws Exception{Map<String,String> f=form(e);LoginResult result=new LoginService().authenticate(req(f,"loginId"),req(f,"password"));if(!result.isSuccess()){json(e,401,"{\"error\":\"invalid credentials\"}");return;}String token=UUID.randomUUID().toString(),csrf=UUID.randomUUID().toString();sessions.put(token,result.getUser());csrfTokens.put(token,csrf);loginAudit(result.getUser(),e);if("ADMIN".equals(result.getUser().getRole()))notifyUser(result.getUser().getUserId(),"ADMIN","관리자 계정으로 로그인했습니다. 관리 로그와 신고 현황을 확인하세요.","/admin");e.getResponseHeaders().add("Set-Cookie","CINEHUB_SESSION="+token+"; Path=/; HttpOnly; SameSite=Lax");e.getResponseHeaders().add("Set-Cookie","CINEHUB_CSRF="+csrf+"; Path=/; SameSite=Lax");json(e,200,"{\"userId\":"+result.getUser().getUserId()+",\"nickname\":\""+esc(result.getUser().getNickname())+"\",\"role\":\""+esc(result.getUser().getRole())+"\"}");}
    private void postList(HttpExchange e)throws IOException{session(e);String board=query(e,"boardId");List<Post> list=board.isBlank()?posts.getAllPosts():posts.getPostsByBoardId(Long.parseLong(board));StringBuilder out=new StringBuilder("{\"posts\":[");for(int i=0;i<list.size();i++){if(i>0)out.append(',');postJson(out,list.get(i));}json(e,200,out.append("]}").toString());}
    private void postDetail(HttpExchange e,long id)throws IOException{User viewer=session(e);Post p=posts.getPostById(id,viewer.getUserId());if(p==null){json(e,404,"{\"error\":\"not found\"}");return;}boolean liked=posts.isLiked(id,viewer.getUserId());StringBuilder out=new StringBuilder();postJson(out,p);out.setLength(out.length()-1);out.append(",\"liked\":").append(liked).append('}');json(e,200,out.toString());}
    private void postCreate(HttpExchange e)throws Exception{User u=session(e);Map<String,String> f=form(e);long board=Long.parseLong(f.getOrDefault("boardId","2"));if(isNoticeBoard(board)&&!"ADMIN".equals(u.getRole())){json(e,403,"{\"error\":\"only administrators can write notices\"}");return;}if(!posts.createPost(new Post(board,u.getUserId(),req(f,"title"),req(f,"content"))))throw new IllegalStateException("create failed");json(e,201,"{\"created\":true}");}
    private void postLike(HttpExchange e,long id)throws Exception{User u=session(e);boolean liked=posts.toggleLike(id,u.getUserId());json(e,200,"{\"liked\":"+liked+",\"likes\":"+posts.getLikeCount(id)+"}");}
    private boolean isNoticeBoard(long boardId){for(Board board:boards.getAllBoards())if(board.getBoardId()==boardId&&"공지사항".equals(board.getBoardName()))return true;return false;}
    private void postUpdate(HttpExchange e,long id)throws Exception{User u=session(e);Map<String,String> f=form(e);if(!posts.updatePost(id,u.getUserId(),req(f,"title"),req(f,"content")))throw new IllegalStateException("not permitted");json(e,200,"{\"updated\":true}");}
    private void postDelete(HttpExchange e,long id)throws Exception{User u=session(e);if(!posts.deletePost(id,u.getUserId()))throw new IllegalStateException("not permitted");json(e,200,"{\"deleted\":true}");}
    private void me(HttpExchange e)throws Exception{User u=session(e);json(e,200,"{\"id\":"+u.getUserId()+",\"loginId\":\""+esc(u.getLoginId())+"\",\"nickname\":\""+esc(u.getNickname())+"\",\"email\":\""+esc(u.getEmail())+"\",\"role\":\""+esc(u.getRole())+"\"}");}
    private void withdraw(HttpExchange e)throws Exception{User u=session(e);if("ADMIN".equals(u.getRole())){json(e,400,"{\"error\":\"administrator accounts cannot withdraw here\"}");return;}if(!users.withdrawUser(u.getUserId())){json(e,400,"{\"error\":\"account withdrawal failed\"}");return;}String token=cookie(e);sessions.remove(token);csrfTokens.remove(token);e.getResponseHeaders().add("Set-Cookie","CINEHUB_SESSION=; Path=/; Max-Age=0; HttpOnly; SameSite=Lax");e.getResponseHeaders().add("Set-Cookie","CINEHUB_CSRF=; Path=/; Max-Age=0; SameSite=Lax");json(e,200,"{\"withdrawn\":true}");}
    private void profileUpdate(HttpExchange e)throws Exception{User u=session(e);Map<String,String> f=form(e);String nickname=req(f,"nickname"),email=req(f,"email");User same=users.findByUserId(u.getUserId());if(!same.getNickname().equals(nickname)&&users.isNicknameDuplicate(nickname)){json(e,409,"{\"error\":\"nickname already used\"}");return;}if(!users.updateProfile(u.getUserId(),nickname,email))throw new IllegalStateException("profile update failed");u.setNickname(nickname);u.setEmail(email);json(e,200,"{\"updated\":true}");}
    private void passwordUpdate(HttpExchange e)throws Exception{User u=session(e);Map<String,String> f=form(e);String current=req(f,"currentPassword"),next=req(f,"newPassword");if(!PasswordHasher.matches(current,u.getPasswordHash())){json(e,401,"{\"error\":\"current password is incorrect\"}");return;}if(next.length()<8){json(e,400,"{\"error\":\"password must be at least 8 characters\"}");return;}String hash=PasswordHasher.hash(next);if(!users.updatePassword(u.getUserId(),hash))throw new IllegalStateException("password update failed");u.setPasswordHash(hash);json(e,200,"{\"updated\":true}");}
    private void boardList(HttpExchange e)throws IOException{List<Board> list=boards.getAllBoards();StringBuilder out=new StringBuilder("{\"boards\":[");for(int i=0;i<list.size();i++){if(i>0)out.append(',');Board b=list.get(i);out.append("{\"id\":").append(b.getBoardId()).append(",\"name\":\"").append(esc(b.getBoardName())).append("\",\"description\":\"").append(esc(b.getBoardDescription())).append("\"}");}json(e,200,out.append("]}").toString());}
    private void boardCreate(HttpExchange e)throws Exception{User u=session(e);if(!"ADMIN".equals(u.getRole())){json(e,403,"{\"error\":\"admin required\"}");return;}Map<String,String> f=form(e);String name=req(f,"name");int order=Integer.parseInt(f.getOrDefault("sortOrder","99"));if(!boards.createBoard(new Board(name,f.getOrDefault("description",""),order)))throw new IllegalStateException("category create failed");json(e,201,"{\"created\":true}");}
    private void boardUpdate(HttpExchange e,long id)throws Exception{if(!isAdmin(e)){json(e,403,"{\"error\":\"admin required\"}");return;}Map<String,String> f=form(e);if(!boards.updateBoard(new Board(id,req(f,"name"),f.getOrDefault("description",""),Integer.parseInt(f.getOrDefault("sortOrder","99")))))throw new IllegalStateException("category update failed");json(e,200,"{\"updated\":true}");}
    private void boardDelete(HttpExchange e,long id)throws Exception{if(!isAdmin(e)){json(e,403,"{\"error\":\"admin required\"}");return;}if(!boards.deleteBoard(id))throw new IllegalStateException("category delete failed");json(e,200,"{\"deleted\":true}");}
    private void contactCreate(HttpExchange e)throws Exception{Map<String,String> f=form(e);try(Connection c=DBConnection.getConnection();PreparedStatement s=c.prepareStatement("INSERT INTO contact_messages (sender_name,email,message) VALUES (?,?,?)")){s.setString(1,req(f,"name"));s.setString(2,req(f,"email"));s.setString(3,req(f,"message"));s.executeUpdate();}json(e,201,"{\"created\":true}");}
    private void commentList(HttpExchange e,long postId)throws IOException{List<Comment> list=comments.getCommentsByPostId(postId);StringBuilder out=new StringBuilder("{\"comments\":[");for(int i=0;i<list.size();i++){if(i>0)out.append(',');Comment c=list.get(i);out.append("{\"id\":").append(c.getCommentId()).append(",\"author\":\"").append(esc(c.getAuthorNickname())).append("\",\"content\":\"").append(esc(c.getContent())).append("\",\"createdAt\":\"").append(esc(c.getCreatedAt())).append("\"}");}json(e,200,out.append("]}").toString());}
    private void commentCreate(HttpExchange e,long postId)throws Exception{User u=session(e);Map<String,String> f=form(e);Post post=posts.getPostById(postId,u.getUserId());if(!comments.createComment(new Comment(postId,u.getUserId(),req(f,"content"))))throw new IllegalStateException("comment create failed");if(post!=null&&post.getUserId()!=u.getUserId())notifyUser(post.getUserId(),"COMMENT",u.getNickname()+"님이 댓글을 남겼습니다.","/post/"+postId);json(e,201,"{\"created\":true}");}
    private void myPosts(HttpExchange e)throws Exception{User u=session(e);List<Post> list=posts.getPostsByUserId(u.getUserId());StringBuilder out=new StringBuilder("{\"posts\":[");for(int i=0;i<list.size();i++){if(i>0)out.append(',');postJson(out,list.get(i));}json(e,200,out.append("]}").toString());}
    private boolean isAdmin(HttpExchange e){try{return "ADMIN".equals(session(e).getRole());}catch(IllegalStateException ignored){return false;}} private boolean loggedIn(HttpExchange e){try{session(e);return true;}catch(IllegalStateException ignored){return false;}}
    private void ensureAuditTables() throws Exception {try(Connection c=DBConnection.getConnection();Statement s=c.createStatement()){try{s.execute("CREATE TABLE login_logs (log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id NUMBER NOT NULL,ip_address VARCHAR2(45) NOT NULL,user_agent VARCHAR2(255),status VARCHAR2(20) NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,CONSTRAINT fk_login_logs_user FOREIGN KEY(user_id) REFERENCES users(user_id) ON DELETE CASCADE)");}catch(java.sql.SQLException ignored){}try{s.execute("CREATE TABLE admin_action_logs (log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,admin_id NUMBER NOT NULL,action_type VARCHAR2(50) NOT NULL,target_type VARCHAR2(30) NOT NULL,target_id NUMBER NOT NULL,reason VARCHAR2(255),ip_address VARCHAR2(45) NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,CONSTRAINT fk_admin_action_logs_admin FOREIGN KEY(admin_id) REFERENCES users(user_id))");}catch(java.sql.SQLException ignored){}try{s.execute("CREATE TABLE post_views (post_id NUMBER NOT NULL,user_id NUMBER NOT NULL,viewed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,CONSTRAINT pk_post_views PRIMARY KEY(post_id,user_id),CONSTRAINT fk_post_views_post FOREIGN KEY(post_id) REFERENCES posts(post_id) ON DELETE CASCADE,CONSTRAINT fk_post_views_user FOREIGN KEY(user_id) REFERENCES users(user_id) ON DELETE CASCADE)");}catch(java.sql.SQLException ignored){}}}
    private String clientIp(HttpExchange e){String forwarded=e.getRequestHeaders().getFirst("X-Forwarded-For");return forwarded==null||forwarded.isBlank()?e.getRemoteAddress().getAddress().getHostAddress():forwarded.split(",")[0].trim();}
    private void loginAudit(User u,HttpExchange e)throws Exception{try(Connection c=DBConnection.getConnection();PreparedStatement s=c.prepareStatement("INSERT INTO login_logs(user_id,ip_address,user_agent,status) VALUES(?,?,?,?)")){s.setLong(1,u.getUserId());s.setString(2,clientIp(e));s.setString(3,Optional.ofNullable(e.getRequestHeaders().getFirst("User-Agent")).orElse(""));s.setString(4,"SUCCESS");s.executeUpdate();}}
    private void adminAudit(HttpExchange e,String action,String targetType,long targetId,String reason)throws Exception{User u=session(e);try(Connection c=DBConnection.getConnection();PreparedStatement s=c.prepareStatement("INSERT INTO admin_action_logs(admin_id,action_type,target_type,target_id,reason,ip_address) VALUES(?,?,?,?,?,?)")){s.setLong(1,u.getUserId());s.setString(2,action);s.setString(3,targetType);s.setLong(4,targetId);s.setString(5,reason);s.setString(6,clientIp(e));s.executeUpdate();}}
    private void adminLogs(HttpExchange e)throws Exception{if(!isAdmin(e)){json(e,403,"{\"error\":\"admin required\"}");return;}StringBuilder out=new StringBuilder("{\"adminActions\":[");try(Connection c=DBConnection.getConnection();PreparedStatement s=c.prepareStatement("SELECT a.log_id,COALESCE(u.nickname,'관리자'),a.action_type,a.target_type,a.target_id,COALESCE(a.reason,''),a.ip_address,TO_CHAR(a.created_at,'YYYY-MM-DD HH24:MI:SS') FROM admin_action_logs a LEFT JOIN users u ON u.user_id=a.admin_id ORDER BY a.log_id DESC FETCH FIRST 100 ROWS ONLY");ResultSet r=s.executeQuery()){int n=0;while(r.next()){if(n++>0)out.append(',');out.append("{\"id\":").append(r.getLong(1)).append(",\"admin\":\"").append(esc(r.getString(2))).append("\",\"action\":\"").append(esc(r.getString(3))).append("\",\"targetType\":\"").append(esc(r.getString(4))).append("\",\"targetId\":").append(r.getLong(5)).append(",\"reason\":\"").append(esc(r.getString(6))).append("\",\"ip\":\"").append(esc(r.getString(7))).append("\",\"createdAt\":\"").append(esc(r.getString(8))).append("\"}");}}out.append("],\"loginLogs\":[");try(Connection c=DBConnection.getConnection();PreparedStatement s=c.prepareStatement("SELECT l.log_id,COALESCE(u.nickname,'사용자'),l.ip_address,l.status,TO_CHAR(l.created_at,'YYYY-MM-DD HH24:MI:SS') FROM login_logs l LEFT JOIN users u ON u.user_id=l.user_id ORDER BY l.log_id DESC FETCH FIRST 100 ROWS ONLY");ResultSet r=s.executeQuery()){int n=0;while(r.next()){if(n++>0)out.append(',');out.append("{\"id\":").append(r.getLong(1)).append(",\"user\":\"").append(esc(r.getString(2))).append("\",\"ip\":\"").append(esc(r.getString(3))).append("\",\"status\":\"").append(esc(r.getString(4))).append("\",\"createdAt\":\"").append(esc(r.getString(5))).append("\"}");}}json(e,200,out.append("]}").toString());}
    private void adminStats(HttpExchange e)throws Exception{if(!isAdmin(e)){json(e,403,"{\"error\":\"admin required\"}");return;}json(e,200,"{\"posts\":"+admin.getTotalPostCount()+",\"comments\":"+admin.getTotalCommentCount()+",\"users\":"+admin.getTotalUserCount()+",\"pendingReports\":"+admin.getPendingReportCount()+"}");}
    private void adminUsers(HttpExchange e)throws Exception{if(!isAdmin(e)){json(e,403,"{\"error\":\"admin required\"}");return;}String q=query(e,"q").trim();int offset=0,limit=10;try{offset=Math.max(0,Integer.parseInt(query(e,"offset")));}catch(Exception ignored){}try{limit=Math.min(20,Math.max(1,Integer.parseInt(query(e,"limit"))));}catch(Exception ignored){}String where=q.isEmpty()?"":" WHERE LOWER(login_id) LIKE LOWER(?) OR LOWER(nickname) LIKE LOWER(?)";String countSql="SELECT COUNT(*) FROM users"+where;String dataSql="SELECT user_id,login_id,nickname,status FROM users"+where+" ORDER BY user_id DESC OFFSET ? ROWS FETCH NEXT ? ROWS ONLY";int total;try(Connection c=DBConnection.getConnection();PreparedStatement s=c.prepareStatement(countSql)){if(!q.isEmpty()){s.setString(1,"%"+q+"%");s.setString(2,"%"+q+"%");}try(ResultSet r=s.executeQuery()){r.next();total=r.getInt(1);}}StringBuilder out=new StringBuilder("{\"total\":"+total+",\"users\":[");try(Connection c=DBConnection.getConnection();PreparedStatement s=c.prepareStatement(dataSql)){int p=1;if(!q.isEmpty()){s.setString(p++,"%"+q+"%");s.setString(p++,"%"+q+"%");}s.setInt(p++,offset);s.setInt(p,limit);try(ResultSet r=s.executeQuery()){int n=0;while(r.next()){if(n++>0)out.append(',');out.append("{\"id\":").append(r.getLong(1)).append(",\"loginId\":\"").append(esc(r.getString(2))).append("\",\"nickname\":\"").append(esc(r.getString(3))).append("\",\"status\":\"").append(esc(r.getString(4))).append("\"}");}}}json(e,200,out.append("]}").toString());}
    private void adminUserStatus(HttpExchange e,long userId)throws Exception{if(!isAdmin(e)){json(e,403,"{\"error\":\"admin required\"}");return;}String status=req(form(e),"status");if(!"ACTIVE".equals(status)&&!"SUSPENDED".equals(status))throw new IllegalArgumentException("invalid status");if(!admin.updateUserStatus(userId,status))throw new IllegalStateException("status update failed");if("SUSPENDED".equals(status)){for(Map.Entry<String,User> entry:sessions.entrySet())if(entry.getValue().getUserId()==userId){sessions.remove(entry.getKey());csrfTokens.remove(entry.getKey());}}adminAudit(e,"USER_STATUS","USER",userId,status);json(e,200,"{\"updated\":true}");}
    private void adminHidePost(HttpExchange e,long postId)throws Exception{if(!isAdmin(e)){json(e,403,"{\"error\":\"admin required\"}");return;}if(!admin.deletePostByAdmin(postId))throw new IllegalStateException("post hide failed");adminAudit(e,"POST_HIDE","POST",postId,"관리자 숨김 처리");json(e,200,"{\"hidden\":true}");}
    private void reportCreate(HttpExchange e)throws Exception{User u=session(e);Map<String,String> f=form(e);String type=req(f,"targetType");if(!"POST".equals(type)&&!"COMMENT".equals(type))throw new IllegalArgumentException("invalid target");if(!reports.reportTarget(type,Long.parseLong(req(f,"targetId")),u.getUserId(),req(f,"reason"))){json(e,409,"{\"error\":\"already reported\"}");return;}notifyAdmins("REPORT","새 신고가 접수되었습니다.","/admin");json(e,201,"{\"created\":true}");}
    private void notificationList(HttpExchange e)throws Exception{User u=session(e);StringBuilder out=new StringBuilder("{\"notifications\":[");try(Connection c=DBConnection.getConnection();PreparedStatement s=c.prepareStatement("SELECT notification_id,type,message,COALESCE(link,''),is_read FROM notifications WHERE user_id=? ORDER BY notification_id DESC FETCH FIRST 50 ROWS ONLY")){s.setLong(1,u.getUserId());try(ResultSet r=s.executeQuery()){int n=0;while(r.next()){if(n++>0)out.append(',');out.append("{\"id\":").append(r.getLong(1)).append(",\"type\":\"").append(esc(r.getString(2))).append("\",\"message\":\"").append(esc(r.getString(3))).append("\",\"link\":\"").append(esc(r.getString(4))).append("\",\"read\":").append("Y".equals(r.getString(5))).append("}");}}}json(e,200,out.append("]}").toString());}
    private void notificationRead(HttpExchange e)throws Exception{User u=session(e);try(Connection c=DBConnection.getConnection();PreparedStatement s=c.prepareStatement("UPDATE notifications SET is_read='Y' WHERE user_id=? AND is_read='N'")){s.setLong(1,u.getUserId());s.executeUpdate();}json(e,200,"{\"updated\":true}");}
    private void notifyUser(long userId,String type,String message,String link)throws Exception{try(Connection c=DBConnection.getConnection();PreparedStatement s=c.prepareStatement("INSERT INTO notifications(user_id,type,message,link) VALUES(?,?,?,?)")){s.setLong(1,userId);s.setString(2,type);s.setString(3,message);s.setString(4,link);s.executeUpdate();}}
    private void notifyAdmins(String type,String message,String link)throws Exception{try(Connection c=DBConnection.getConnection();PreparedStatement s=c.prepareStatement("SELECT user_id FROM users WHERE role='ADMIN' AND status='ACTIVE'" );ResultSet r=s.executeQuery()){while(r.next())notifyUser(r.getLong(1),type,message,link);}}
    private void adminReports(HttpExchange e)throws Exception{if(!isAdmin(e)){json(e,403,"{\"error\":\"admin required\"}");return;}List<ReportDTO> list=admin.getAllReports();StringBuilder out=new StringBuilder("{\"reports\":[");for(int i=0;i<list.size();i++){if(i>0)out.append(',');ReportDTO r=list.get(i);out.append("{\"id\":").append(r.getReportId()).append(",\"type\":\"").append(esc(r.getTargetType())).append("\",\"targetId\":").append(r.getTargetId()).append(",\"reason\":\"").append(esc(r.getReason())).append("\",\"status\":\"").append(esc(r.getStatus())).append("\",\"reporter\":\"").append(esc(r.getReporterNickname())).append("\"}");}json(e,200,out.append("]}").toString());}
    private void adminReportUpdate(HttpExchange e,long reportId)throws Exception{if(!isAdmin(e)){json(e,403,"{\"error\":\"admin required\"}");return;}String status=req(form(e),"status");if(!"RESOLVED".equals(status)&&!"REJECTED".equals(status))throw new IllegalArgumentException("invalid status");if(!admin.updateReportStatus(reportId,status))throw new IllegalStateException("report update failed");adminAudit(e,"REPORT_"+status,"REPORT",reportId,status);json(e,200,"{\"updated\":true}");}
    private void movieSearch(HttpExchange e)throws Exception{session(e);String q=query(e,"q");List<Long> semantic=List.of();try{semantic=rag.search(q);}catch(Exception ignored){}List<Long> lexical=movieKeywordIds(q);java.util.LinkedHashSet<Long> merged=new java.util.LinkedHashSet<>();merged.addAll(semantic);merged.addAll(lexical);if(!merged.isEmpty()){List<Long> candidates=new java.util.ArrayList<>(merged);candidates=candidates.subList(0,Math.min(10,candidates.size()));OpenAiMovieAdvisor.Recommendation selected=new OpenAiMovieAdvisor.Recommendation(candidates.get(0),"DB와 의미 검색 결과에서 선택한 영화입니다.");try{selected=movieAdvisor.chooseFromCandidates(q,candidates,movieTitles(candidates));}catch(Exception ignored){}movieByIds(e,List.of(selected.getMovieId()),selected.getReason());return;}json(e,200,"{\"results\":[]}");}
    private List<Long> movieKeywordIds(String text)throws Exception{String[] raw=text.split("\\s+");List<String> terms=new java.util.ArrayList<>();for(String word:raw){String t=word.length()>2?word.substring(0,2):word;if(t.length()>1)terms.add(t);}if(terms.isEmpty())return List.of();StringBuilder sql=new StringBuilder("SELECT movie_id FROM movies WHERE ");for(int i=0;i<terms.size();i++){if(i>0)sql.append(" OR ");sql.append("LOWER(title) LIKE LOWER(?) OR LOWER(original_title) LIKE LOWER(?) OR DBMS_LOB.INSTR(LOWER(overview),LOWER(?))>0");}sql.append(" ORDER BY popularity DESC FETCH FIRST 12 ROWS ONLY");List<Long> ids=new java.util.ArrayList<>();try(Connection c=DBConnection.getConnection();PreparedStatement s=c.prepareStatement(sql.toString())){int p=1;for(String term:terms){s.setString(p++,"%"+term+"%");s.setString(p++,"%"+term+"%");s.setString(p++,term);}try(ResultSet r=s.executeQuery()){while(r.next())ids.add(r.getLong(1));}}return ids;}
    private List<String> movieTitles(List<Long> ids)throws Exception{if(ids.isEmpty())return List.of();StringBuilder in=new StringBuilder();for(int i=0;i<ids.size();i++){if(i>0)in.append(',');in.append('?');}java.util.Map<Long,String> found=new java.util.HashMap<>();try(Connection c=DBConnection.getConnection();PreparedStatement s=c.prepareStatement("SELECT movie_id,title FROM movies WHERE movie_id IN ("+in+")")){for(int i=0;i<ids.size();i++)s.setLong(i+1,ids.get(i));try(ResultSet r=s.executeQuery()){while(r.next())found.put(r.getLong(1),r.getString(2));}}List<String> titles=new java.util.ArrayList<>();for(Long id:ids)titles.add(found.getOrDefault(id,"제목 없음"));return titles;}
    private void movieByIds(HttpExchange e,List<Long> ids,String reason)throws Exception{StringBuilder in=new StringBuilder();for(int i=0;i<ids.size();i++){if(i>0)in.append(',');in.append('?');}java.util.Map<Long,String> values=new java.util.HashMap<>();try(Connection c=DBConnection.getConnection();PreparedStatement s=c.prepareStatement("SELECT movie_id,title,COALESCE(original_title,''),DBMS_LOB.SUBSTR(overview,4000,1),COALESCE(poster_path,'') FROM movies WHERE movie_id IN ("+in+")")){for(int i=0;i<ids.size();i++)s.setLong(i+1,ids.get(i));try(ResultSet r=s.executeQuery()){while(r.next()){StringBuilder one=new StringBuilder();movieJson(one,r);one.setLength(one.length()-1);one.append(",\"reason\":\"").append(esc(reason)).append("\"}");values.put(r.getLong(1),one.toString());}}}StringBuilder out=new StringBuilder("{\"results\":[");for(Long id:ids)if(values.containsKey(id)){if(out.charAt(out.length()-1)!='[')out.append(',');out.append(values.get(id));}json(e,200,out.append("]}").toString());}
    private void movieRandom(HttpExchange e)throws Exception{session(e);List<Long> ids=new java.util.ArrayList<>();List<String> titles=new java.util.ArrayList<>();try(Connection c=DBConnection.getConnection();PreparedStatement s=c.prepareStatement("SELECT movie_id,title FROM movies ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 30 ROWS ONLY");ResultSet r=s.executeQuery()){while(r.next()){ids.add(r.getLong(1));titles.add(r.getString(2));}}if(ids.isEmpty()){json(e,404,"{\"error\":\"no movies imported\"}");return;}OpenAiMovieAdvisor.Recommendation selected=new OpenAiMovieAdvisor.Recommendation(ids.get(0),"오늘 새로운 영화 한 편을 만나보세요.");try{selected=movieAdvisor.chooseFromCandidates("오늘 가볍게 볼 랜덤 추천",ids,titles);}catch(Exception ignored){}movieByIds(e,List.of(selected.getMovieId()),selected.getReason());}
    private void moviePopular(HttpExchange e)throws Exception{session(e);StringBuilder out=new StringBuilder("{\"results\":[");try(Connection c=DBConnection.getConnection();PreparedStatement s=c.prepareStatement("SELECT movie_id,title,COALESCE(original_title,''),DBMS_LOB.SUBSTR(overview,4000,1),COALESCE(poster_path,'') FROM movies ORDER BY popularity DESC NULLS LAST, movie_id DESC FETCH FIRST 5 ROWS ONLY");ResultSet r=s.executeQuery()){while(r.next()){if(out.charAt(out.length()-1)!='[')out.append(',');movieJson(out,r);}}json(e,200,out.append("]}").toString());}
    private void movieDetail(HttpExchange e,long movieId)throws Exception{session(e);String sql="SELECT movie_id,title,COALESCE(original_title,''),DBMS_LOB.SUBSTR(overview,4000,1),COALESCE(poster_path,'') FROM movies WHERE movie_id=?";try(Connection c=DBConnection.getConnection();PreparedStatement s=c.prepareStatement(sql)){s.setLong(1,movieId);try(ResultSet r=s.executeQuery()){if(!r.next()){json(e,404,"{\"error\":\"movie not found\"}");return;}StringBuilder out=new StringBuilder();movieJson(out,r);json(e,200,out.toString());}}}
    private static void movieJson(StringBuilder out,ResultSet r)throws Exception{String poster=r.getString(5);out.append("{\"id\":").append(r.getLong(1)).append(",\"title\":\"").append(esc(r.getString(2))).append("\",\"originalTitle\":\"").append(esc(r.getString(3))).append("\",\"overview\":\"").append(esc(r.getString(4))).append("\",\"poster\":\"").append(esc(poster==null||poster.isBlank()?"":"https://image.tmdb.org/t/p/w500"+poster)).append("\"}");}
    private static void postJson(StringBuilder out,Post p){out.append("{\"id\":").append(p.getPostId()).append(",\"boardId\":").append(p.getBoardId()).append(",\"authorId\":").append(p.getUserId()).append(",\"title\":\"").append(esc(p.getTitle())).append("\",\"content\":\"").append(esc(p.getContent())).append("\",\"author\":\"").append(esc(p.getAuthorNickname())).append("\",\"createdAt\":\"").append(esc(p.getCreatedAt())).append("\",\"views\":").append(p.getViewCount()).append(",\"likes\":").append(p.getLikeCount()).append("}");}
    private static void staticFile(HttpExchange e,String requested)throws IOException{Path root=Path.of("webapp").toAbsolutePath().normalize();Path file=root.resolve(requested).normalize();if(!file.startsWith(root)||!Files.isRegularFile(file)){send(e,404,"text/plain","Not found");return;}String type=Files.probeContentType(file);byte[] b=Files.readAllBytes(file);e.getResponseHeaders().set("Content-Type",type==null?"application/octet-stream":type);e.sendResponseHeaders(200,b.length);e.getResponseBody().write(b);e.close();}
    private static String layout(String title,String content,String script){title=title.replace("Marcian Blog","CINEHUB");return "<!doctype html><html lang='ko'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>"+title+"</title>"
        +"<link rel='stylesheet' href='/static/assets/css/style.css'><link rel='stylesheet' href='/static/assets/css/widgets.css'><link rel='stylesheet' href='/static/assets/css/responsive.css'><link rel='stylesheet' href='/static/assets/css/post-layout.css'>"
        +"<style>body{background:#f7f8fa}.main-header{background:#fff}.site-logo img{max-height:45px}.blog-wrap{max-width:1180px;margin:0 auto;padding:42px 20px}.hero{background:#fff;border:1px solid #eee;border-radius:12px;padding:48px;margin-bottom:28px}.hero h1{font-size:38px;margin:0 0 14px}.post-card{display:block;background:#fff;border:1px solid #eee;border-radius:10px;padding:24px;margin:0 0 15px;color:inherit}.post-card:hover{border-color:#0ea5e9}.post-card h3{margin:0 0 9px}.muted{color:#777}.form-box{max-width:580px;margin:12px auto;background:#fff;border:1px solid #eee;border-radius:12px;padding:32px}.form-box input,.form-box textarea,.form-box select{width:100%;padding:12px;margin:7px 0 18px;border:1px solid #ddd;border-radius:5px}.form-box textarea{min-height:260px}.btn-main{background:#0ea5e9;color:white;border:0;border-radius:5px;padding:12px 20px;cursor:pointer}.nav-links a{margin-left:18px;color:#222}.post-body{white-space:pre-wrap;line-height:1.85}</style></head><body>"
        +"<header class='main-header header-style-1 font-heading'><div class='header-top'><div class='container'><div class='row pt-20 pb-20'><div class='col-md-3 col-xs-6'><a class='site-logo' href='/' aria-label='CINEHUB 홈'>CINEHUB</a></div></div></div></div><div class='header-sticky'><div class='container align-self-center'><div class='main-nav d-none d-lg-block float-left'><nav><ul class='main-menu d-none d-lg-inline font-small'><li><a href='/'>홈</a></li><li><a href='/movies'>영화 추천</a></li><li><a href='/about-us'>소개</a></li><li><a href='/posts'>게시글</a></li><li><a href='/mypage'>마이페이지</a></li><li id='navNotifications' style='display:none'><a href='/notifications'>알림</a></li><li id='navAdmin' style='display:none'><a href='/admin'>관리자</a></li></ul></nav></div><div class='float-right header-tools text-muted font-small'><ul class='list-inline d-none d-md-inline'><li class='list-inline-item'><a href='/new-post'>글쓰기</a></li><li class='list-inline-item' id='navLogin'><a href='/login'>로그인</a></li><li class='list-inline-item' id='navRegister'><a href='/register'>회원가입</a></li><li class='list-inline-item' id='navUser' style='display:none'><a id='navMyPage' href='/mypage'></a></li><li class='list-inline-item' id='navLogout' style='display:none'><a href='#' onclick='logoutNow();return false;'>로그아웃</a></li></ul></div><div class='clearfix'></div></div></div></header>"
        +"<main>"+content+"</main><footer class='main-footer bg-grey pt-50 pb-30'><div class='container'><p class='text-center text-muted'>CINEHUB · 영화 탐색 커뮤니티</p></div></footer><script>"+COMMON_JS+script+";fetch('/api/me').then(function(r){return r.ok?r.json():null;}).then(function(u){if(u)document.body.classList.add('logged-in');});</script></body></html>";}
    private static String homePage(){return layout("CINEHUB", "<section class='entry-header entry-header-style-2' style=\"background-image:linear-gradient(90deg,rgba(0,0,0,.76),rgba(0,0,0,.42),rgba(0,0,0,.22)),url('/static/assets/imgs/cinehub-hero-theater.png')!important\"><div class='container entry-header-content'><h1>오늘, 어떤 영화를 볼까요?</h1><h2>장르와 분위기를 알려주면 CINEHUB가 당신에게 어울리는 한 편을 찾아드려요.</h2></div></section><div class='container'><div class='hot-tags'><div class='widget-header-3'><h5 class='widget-title'>실시간 인기 영화 TOP 5</h5></div><div id='movieResults'><p class='muted'>인기 영화를 불러오는 중입니다.</p></div></div><div class='loop-grid'><div class='widget-header-3'><h5 class='widget-title'>커뮤니티 실시간 인기글</h5></div><div id='posts'><p class='muted'>게시글을 불러오는 중입니다.</p></div></div></div>", "loadPopularMovies();loadPosts('posts',5);");}
    private static String postsPage(){return layout("게시글 | CINEHUB", "<div class='container'><div class='widget-header-3'><h1 class='widget-title'>전체 게시글</h1></div><div id='posts'><p class='muted'>게시글을 불러오는 중입니다.</p></div><nav class='pagination' id='postPagination'></nav></div>", "fetch('/api/posts').then(r=>r.json()).then(d=>{let a=d.posts||[],page=1,draw=()=>{let pages=Math.max(1,Math.ceil(a.length/10));document.getElementById('posts').innerHTML=a.slice((page-1)*10,page*10).map(p=>'<a class=\\\"post-card\\\" href=\\\"/post/'+p.id+'\\\"><h3>'+safe(p.title)+'</h3><p>'+safe(p.content).slice(0,140)+'</p><small>'+safe(p.author)+' · '+safe(p.createdAt)+'</small></a>').join('')||'<p>게시글이 없습니다.</p>';document.getElementById('postPagination').innerHTML=Array.from({length:pages},(_,i)=>'<button class=\\\"page-number '+(page===i+1?'active':'')+'\\\">'+(i+1)+'</button>').join('');[...document.querySelectorAll('#postPagination button')].forEach((b,i)=>b.onclick=()=>{page=i+1;draw()});};draw()});");}
    private static String categoryPostsPage(long boardId){return layout("카테고리 게시글 | Marcian Blog", "<div class='container'><div class='widget-header-3'><h1 class='widget-title'>카테고리 게시글</h1></div><div id='posts'><p class='muted'>게시글을 불러오는 중입니다.</p></div></div>", "loadBoardPosts('posts',"+boardId+");");}
    private static String myPage(){return layout("마이페이지 | Marcian Blog", "<div class='container'><section class='hero'><span class='muted'>MY PAGE</span><h1 id='myTitle'>마이페이지</h1><p id='myInfo' class='muted'>내 정보를 불러오는 중입니다.</p><a class='btn-main' id='profileLink' href='#'>프로필 수정</a> <a class='btn-main' id='passwordLink' href='#'>비밀번호 변경</a> <button class='btn-main withdraw-button' type='button' onclick='withdrawAccount()'>회원 탈퇴</button></section><div class='widget-header-3'><h5 class='widget-title'>내가 작성한 글</h5></div><div id='posts'></div></div>","loadMyPage();");}
    private static String notificationsPage(){return layout("알림 | Marcian Blog","<div class='container'><h1>알림 센터</h1><div id='notifications'><p class='muted'>알림을 불러오는 중입니다.</p></div></div>","loadNotifications();");}
    private static String adminPage(){return layout("관리자 | CINEHUB","<div class='container admin-dashboard'><section class='hero admin-hero'><span class='muted'>ADMIN</span><h1>관리자 대시보드</h1><div id='stats'>통계를 불러오는 중입니다.</div><p><a class='btn-main' href='/admin/logs'>관리 로그 보기</a></p></section><h2>회원 관리</h2><div class='admin-search'><input id='adminUserSearch' oninput='filterAdminUsers()' placeholder='닉네임 또는 아이디 검색'><button onclick='filterAdminUsers()'>검색</button></div><div id='users'></div><h2>게시글 관리</h2><p class='muted'>한 페이지에 5개씩 표시됩니다. 숨김 처리한 글은 일반 게시글 목록에서 즉시 제외됩니다.</p><div class='admin-search'><input id='adminPostSearch' oninput='loadAdminPostsCompact()' placeholder='게시글 제목 또는 작성자 검색'><button onclick='loadAdminPostsCompact()'>검색</button></div><nav class='pagination pagination-top' id='adminPostPaginationTop'></nav><div id='adminPosts'></div><nav class='pagination' id='adminPostPagination'></nav><h2>신고 관리</h2><div id='reports'></div></div>","function filterAdminUsers(){var q=document.getElementById('adminUserSearch').value.toLowerCase();Array.prototype.forEach.call(document.querySelectorAll('#users .post-card'),function(x){x.style.display=x.textContent.toLowerCase().indexOf(q)>=0?'block':'none';});}function loadAdminPostsCompact(){fetch('/api/posts').then(function(r){return r.json();}).then(function(d){var a=d.posts||[],q=document.getElementById('adminPostSearch').value.toLowerCase(),shown=q?a.filter(function(p){return (p.title+' '+p.author).toLowerCase().indexOf(q)>=0;}):a,page=1,draw=function(){var pages=Math.max(1,Math.ceil(shown.length/5));document.getElementById('adminPosts').innerHTML=shown.slice((page-1)*5,page*5).map(function(p){return '<div class=\"post-card admin-post-row\"><b>'+safe(p.title)+'</b><span>'+safe(p.author)+'</span><a class=\"btn-main\" href=\"/post/'+p.id+'\">보기</a><button class=\"btn-main\" onclick=\"hideAdminPost('+p.id+')\">숨김</button></div>';}).join('')||'<p class=\"muted\">검색 결과가 없습니다.</p>';var controls=Array.from({length:pages},function(_,i){return '<button class=\"page-number '+(page===i+1?'active':'')+'\">'+(i+1)+'</button>';}).join('');document.getElementById('adminPostPaginationTop').innerHTML=controls;document.getElementById('adminPostPagination').innerHTML=controls;Array.prototype.forEach.call(document.querySelectorAll('#adminPostPaginationTop button,#adminPostPagination button'),function(b,i){b.onclick=function(){page=i%pages+1;draw();};});};draw();});}function hideAdminPost(id){if(!confirm('이 게시글을 숨길까요?'))return;fetch('/api/admin/posts/'+id+'/hide',{method:'PUT'}).then(function(r){if(r.ok){loadAdminPostsCompact();loadAdmin();}});}loadAdmin();loadAdminPostsCompact();loadReports();");}
    private static String categoryManagePage(){return layout("카테고리 관리 | Marcian Blog","<div class='container'><form class='form-box' id='boardForm'><h1>게시판 추가</h1><label>이름</label><input name='name' required><label>설명</label><input name='description'><label>정렬 순서</label><input name='sortOrder' type='number' value='99'><button class='btn-main'>추가</button><p id='message'></p></form><h2>게시판 관리</h2><div id='boards'></div></div>","bindBoardForm();loadBoards();");}
    private static String loginPage(){return layout("로그인 | Marcian Blog", "<form class='form-box' id='loginForm'><h1>로그인</h1><label>아이디</label><input name='loginId' required><label>비밀번호</label><input type='password' name='password' required><button class='btn-main'>로그인</button><p class='muted'>계정이 없나요? <a href='/register'>회원가입</a></p></form>", "bindAuthForm('loginForm','/api/auth/login','/');");}
    private static String registerPage(){return layout("회원가입 | Marcian Blog", "<form class='form-box' id='registerForm'><h1>회원가입</h1><label>아이디</label><input name='loginId' required><label>비밀번호</label><input type='password' name='password' required><label>닉네임</label><input name='nickname' required><label>이메일</label><input name='email' type='email' required><button class='btn-main'>가입하기</button><p class='muted'>이미 계정이 있나요? <a href='/login'>로그인</a></p></form>", "bindAuthForm('registerForm','/api/auth/register','/login');");}
    private static String editorPage(){return layout("글쓰기 | Marcian Blog", "<form class='form-box' id='postForm'><h1>새 글 작성</h1><label>게시판</label><select name='boardId'><option value='2'>자유게시판</option><option value='3'>영화 추천</option></select><p class='muted'>공지사항은 관리자 계정만 작성할 수 있습니다.</p><label>제목</label><input name='title' required><label>내용</label><textarea name='content' required></textarea><button class='btn-main'>등록하기</button><p id='message'></p></form>", "enableNoticeForAdmin();bindForm('postForm','/api/posts','/posts');");}
    private static String editPage(long id){return layout("글 수정 | Marcian Blog", "<form class='form-box' id='editForm'><h1>글 수정</h1><label>제목</label><input name='title' required><label>내용</label><textarea name='content' required></textarea><button class='btn-main'>수정 저장</button><p id='message'></p></form>", "loadPostEditor("+id+");");}
    private static String detailPage(long id){return layout("게시글 | Marcian Blog", "<article class='form-box' id='post'><p class='muted'>게시글을 불러오는 중입니다.</p></article><section class='form-box'><h3>댓글</h3><div id='comments'></div><form id='commentForm'><textarea name='content' placeholder='댓글을 입력하세요' required></textarea><button class='btn-main'>댓글 등록</button><p id='message'></p></form></section><section class='form-box'><h3>신고</h3><form id='reportForm'><input type='hidden' name='targetType' value='POST'><input type='hidden' name='targetId' value='"+id+"'><input name='reason' placeholder='신고 사유' required><button class='btn-main'>신고하기</button><p id='reportMessage'></p></form></section>", "loadPostDetail("+id+");bindReport();loadComments("+id+");bindComment("+id+");");}
    private static String infoPage(String title,String heading,String text){return layout(title+" | CINEHUB","<section class='hero'><span class='muted'>CINEHUB</span><h1>"+heading+"</h1><p>"+text+"</p><a class='btn-main' href='/posts'>게시글 보기</a></section>","");}
    private static String contactPage(){return layout("Contact us | Marcian Blog","<form class='form-box' id='contactForm'><h1>Contact us</h1><label>이름</label><input name='name' placeholder='이름' required><label>이메일</label><input name='email' type='email' placeholder='email@example.com' required><label>메시지</label><textarea name='message' placeholder='문의 내용을 남겨주세요' required></textarea><button class='btn-main'>보내기</button><p id='message'></p></form>","bindForm('contactForm','/api/contact','/contact-us');");}
    private static String moviesPage(){return layout("Movies | Marcian Blog","<section class='hero'><div class='container'><span class='muted'>MOVIE RECOMMENDATION</span><h1>오늘 볼 영화를 찾아보세요</h1><p>제목, 장르, 분위기로 영화를 검색할 수 있습니다.</p><div class='movie-search-bar'><input id='movieQuery' placeholder='예: 우주를 떠도는 과학자'><button class='btn-main' id='movieSearchButton'>영화 검색</button><button class='btn-main' id='movieRandomButton'>랜덤 추천</button></div></div></section><section class='container movie-results-section'><h2>영화 추천</h2><p class='muted' id='movieStatus'>검색어를 입력해 주세요.</p><div id='movieResults'></div></section>","bindMovieSearch();");}
    private static String movieDetailPage(long movieId){return layout("영화 상세 | Marcian Blog","<section class='container movie-detail' id='movieDetail'><p class='muted'>영화 정보를 불러오는 중입니다.</p></section>","loadMovieDetail("+movieId+");");}
    private static String searchPage(){return layout("Search | Marcian Blog","<section class='hero'><h1>검색</h1><form action='/page-search'><input name='q' placeholder='검색어 입력' style='padding:12px;width:70%;border:1px solid #ddd'><button class='btn-main'>검색</button></form></section><div id='posts'></div>","loadPosts('posts',100);");}
    private static String profilePage(String heading){return layout(heading+" | Marcian Blog","<section class='hero'><span class='muted'>MY PAGE</span><h1>"+heading+"</h1><p>사용자 정보와 작성한 글을 확인합니다.</p></section><div id='posts'></div>","loadPosts('posts',100);");}
    private static String profileEditPage(){return layout("프로필 수정 | Marcian Blog","<form class='form-box' id='profileForm'><h1>프로필 수정</h1><label>닉네임</label><input name='nickname' required><label>이메일</label><input name='email' type='email' required><button class='btn-main'>저장</button><p id='message'></p></form>","loadProfile();bindPut('profileForm','/api/me/profile','/');");}
    private static String passwordPage(){return layout("비밀번호 변경 | Marcian Blog","<form class='form-box' id='passwordForm'><h1>비밀번호 변경</h1><label>현재 비밀번호</label><input name='currentPassword' type='password' required><label>새 비밀번호</label><input name='newPassword' type='password' required><button class='btn-main'>변경하기</button><p id='message'></p></form>","bindPut('passwordForm','/api/me/password','/');");}
    private static final String COMMON_JS="function safe(v){var d=document.createElement('div');d.textContent=v||'';return d.innerHTML;}function csrfToken(){var m=document.cookie.match(/(?:^|; )CINEHUB_CSRF=([^;]+)/);return m?decodeURIComponent(m[1]):'';}var originalFetch=window.fetch;window.fetch=function(url,options){options=options||{};var method=(options.method||'GET').toUpperCase();if(method!=='GET'&&method!=='HEAD'){options.headers=options.headers||{};if(options.headers instanceof Headers)options.headers.set('X-CSRF-Token',csrfToken());else options.headers['X-CSRF-Token']=csrfToken();}return originalFetch(url,options);};"
        +"function loadPosts(t,n){fetch('/api/posts').then(function(r){return r.json();}).then(function(d){var a=d.posts||[];document.getElementById(t).innerHTML=a.slice(0,n).map(function(p){return '<a data-list-stats=\\\"1\\\" class=\\\"post-card\\\" href=\\\"/post/'+p.id+'\\\"><p class=\\\"muted\\\">'+safe(p.author)+' · '+safe(p.createdAt)+'</p><h3>'+safe(p.title)+'</h3><p class=\\\"muted\\\">'+safe((p.content||'').slice(0,120))+'</p><small class=\\\"muted post-list-stats\\\">조회 '+p.views+' · 좋아요 '+p.likes+'</small></a>';}).join('')||'<p class=\\\"muted\\\">아직 등록된 글이 없습니다.</p>';}).catch(function(){document.getElementById(t).innerHTML='<p class=\\\"muted\\\">게시글을 불러오지 못했습니다.</p>';});}"
        +"function loadBoardPosts(t,id){fetch('/api/posts?boardId='+id).then(function(r){return r.json();}).then(function(d){var a=d.posts||[];document.getElementById(t).innerHTML=a.map(function(p){return '<a data-list-stats=\\\"1\\\" class=\\\"post-card\\\" href=\\\"/post/'+p.id+'\\\"><p class=\\\"muted\\\">'+safe(p.author)+' · '+safe(p.createdAt)+'</p><h3>'+safe(p.title)+'</h3><p class=\\\"muted\\\">'+safe((p.content||'').slice(0,120))+'</p><small class=\\\"muted post-list-stats\\\">조회 '+p.views+' · 좋아요 '+p.likes+'</small></a>';}).join('')||'<p class=\\\"muted\\\">이 카테고리에 등록된 글이 없습니다.</p>';});}"
        +"function loadHomePosts(){fetch('/api/posts').then(function(r){return r.json();}).then(function(d){var a=d.posts||[],out=document.getElementById('homePosts');if(!a.length){out.innerHTML='<p class=\\\"muted\\\">아직 등록된 글이 없습니다.</p>';return;}var hero=a[0];var card=function(p,i){var img='https://images.unsplash.com/photo-'+(i%2?'1499750310107-5fef28a66643':'1516321318423-f06f85e504b3')+'?auto=format&fit=crop&w=700&q=75';return '<article class=\\\"col-lg-4 col-md-6 mb-30 wow fadeInUp animated\\\"><div class=\\\"post-card-1 border-radius-10 hover-up\\\"><div class=\\\"post-thumb thumb-overlay img-hover-slide position-relative\\\" style=\\\"height:210px;background-image:url('+img+')\\\"><a class=\\\"img-link\\\" href=\\\"/post/'+p.id+'\\\"></a></div><div class=\\\"post-content p-30\\\"><div class=\\\"entry-meta meta-1 font-x-small text-uppercase\\\"><span>'+safe(p.author)+' · '+safe(p.createdAt)+'</span></div><h5 class=\\\"post-title mb-20 font-weight-900\\\"><a href=\\\"/post/'+p.id+'\\\">'+safe(p.title)+'</a></h5><p class=\\\"muted\\\">'+safe((p.content||'').slice(0,100))+'</p></div></div></article>';};out.innerHTML='<div class=\\\"row\\\"><div class=\\\"col-lg-8 mb-30\\\"><div class=\\\"post-card-1 border-radius-10 overflow-hidden\\\"><div class=\\\"thumb-overlay img-hover-slide position-relative\\\" style=\\\"height:360px;background-image:url(https://images.unsplash.com/photo-1551829142-d9b8cf2c9232?auto=format&fit=crop&w=1000&q=80)\\\"><a class=\\\"img-link\\\" href=\\\"/post/'+hero.id+'\\\"></a><div class=\\\"post-content-overlay text-white ml-30 mr-30 pb-30\\\"><h2 class=\\\"font-weight-900\\\"><a class=\\\"text-white\\\" href=\\\"/post/'+hero.id+'\\\">'+safe(hero.title)+'</a></h2><p>'+safe((hero.content||'').slice(0,140))+'</p></div></div></div></div><div class=\\\"col-lg-4 mb-30\\\">'+(a[1]?card(a[1],1):'')+'</div></div><div class=\\\"row\\\">'+a.slice(2,11).map(card).join('')+'</div>';});}"
        +";function bindForm(i,u,next){document.getElementById(i).addEventListener('submit',function(e){e.preventDefault();fetch(u,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(new FormData(e.target))}).then(function(r){if(r.ok){location.href=next;return null;}return r.json();}).then(function(d){if(d)document.getElementById('message').textContent=d.error||'처리하지 못했습니다.';});});}function bindAuthForm(i,u,next){document.getElementById(i).addEventListener('submit',function(e){e.preventDefault();fetch(u,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(new FormData(e.target))}).then(function(r){if(r.ok){location.href=next;return null;}return r.json();}).then(function(d){if(!d)return;var m=d.error||'처리하지 못했습니다.';if(m==='invalid credentials')m='아이디 또는 비밀번호가 올바르지 않습니다.';else if(m==='duplicate account')m='이미 사용 중인 아이디 또는 닉네임입니다.';else if(m==='invalid account format')m='아이디와 비밀번호 형식을 확인해 주세요.';alert(m);});});}"
        +"function bindPut(i,u,next){document.getElementById(i).addEventListener('submit',function(e){e.preventDefault();fetch(u,{method:'PUT',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(new FormData(e.target))}).then(function(r){if(r.ok){location.href=next;return null;}return r.json();}).then(function(d){if(d)document.getElementById('message').textContent=d.error||'처리하지 못했습니다.';});});}"
        +"function loadProfile(){fetch('/api/me').then(function(r){if(!r.ok)throw 0;return r.json();}).then(function(u){document.querySelector('[name=nickname]').value=u.nickname;document.querySelector('[name=email]').value=u.email||'';}).catch(function(){location.href='/login';});}"
        +"function loadComments(id){fetch('/api/posts/'+id+'/comments').then(function(r){return r.json();}).then(function(d){document.getElementById('comments').innerHTML=(d.comments||[]).map(function(c){return '<div class=\\\"post-card\\\"><b>'+safe(c.author)+'</b><p>'+safe(c.content)+'</p><small class=\\\"muted\\\">'+safe(c.createdAt)+'</small></div>';}).join('')||'<p class=\\\"muted\\\">첫 댓글을 남겨보세요.</p>';});}"
        +"function bindComment(id){document.getElementById('commentForm').addEventListener('submit',function(e){e.preventDefault();fetch('/api/posts/'+id+'/comments',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(new FormData(e.target))}).then(function(r){if(r.ok){e.target.reset();loadComments(id);}else{location.href='/login';}});});}"
        +"function bindReport(){document.getElementById('reportForm').addEventListener('submit',function(e){e.preventDefault();fetch('/api/reports',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(new FormData(e.target))}).then(function(r){document.getElementById('reportMessage').textContent=r.ok?'신고가 접수되었습니다.':'신고는 로그인 후 한 번만 가능합니다.';});});}"
        +"function loadPostDetail(id){Promise.all([fetch('/api/posts/'+id).then(function(r){return r.json();}),fetch('/api/me').then(function(r){return r.ok?r.json():null;})]).then(function(a){var p=a[0],u=a[1],actions='';if(u&&(u.id===p.authorId||u.role==='ADMIN'))actions='<p><a class=\\\"btn-main\\\" href=\\\"/edit-post/'+id+'\\\">수정</a> <button class=\\\"btn-main\\\" onclick=\\\"deletePost('+id+')\\\">삭제</button></p>';document.getElementById('post').innerHTML='<p class=\\\'muted\\\'>'+safe(p.author)+' · '+safe(p.createdAt)+'</p><h1>'+safe(p.title)+'</h1><hr><div class=\\\'post-body\\\'>'+safe(p.content)+'</div>'+actions;}).catch(function(){document.getElementById('post').textContent='게시글을 찾을 수 없습니다.';});}function deletePost(id){if(!confirm('게시글을 삭제할까요?'))return;fetch('/api/posts/'+id,{method:'DELETE'}).then(function(r){if(r.ok)location.href='/posts';});}function loadPostEditor(id){fetch('/api/posts/'+id).then(function(r){return r.json();}).then(function(p){document.querySelector('[name=title]').value=p.title;document.querySelector('[name=content]').value=p.content;document.getElementById('editForm').addEventListener('submit',function(e){e.preventDefault();fetch('/api/posts/'+id,{method:'PUT',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(new FormData(e.target))}).then(function(r){if(r.ok)location.href='/post/'+id;else document.getElementById('message').textContent='작성자만 수정할 수 있습니다.';});});});}"
        +"function loadMyPage(){fetch('/api/me').then(function(r){if(!r.ok)throw 0;return r.json();}).then(function(u){document.getElementById('myTitle').textContent=u.nickname+'님의 마이페이지';document.getElementById('myInfo').textContent=u.loginId+' · '+u.email;document.getElementById('profileLink').href='/user/'+u.id+'/edit-profile';document.getElementById('passwordLink').href='/user/'+u.id+'/password-reset';return fetch('/api/my/posts');}).then(function(r){return r.json();}).then(function(d){var a=d.posts||[];document.getElementById('posts').innerHTML=a.map(function(p){return '<a class=\\\"post-card\\\" href=\\\"/post/'+p.id+'\\\"><h3>'+safe(p.title)+'</h3><p class=\\\"muted\\\">'+safe(p.createdAt)+'</p></a>';}).join('')||'<p class=\\\"muted\\\">작성한 게시글이 없습니다.</p>';}).catch(function(){location.href='/login';});}"
        +"function enableNoticeForAdmin(){fetch('/api/me').then(function(r){return r.ok?r.json():null;}).then(function(u){if(u&&u.role==='ADMIN'){var o=document.createElement('option');o.value='1';o.textContent='공지사항';document.querySelector('[name=boardId]').prepend(o);}});}"
        +"function loadPopularMovies(){var out=document.getElementById('movieResults');if(!out)return;fetch('/api/movies/popular').then(function(r){return r.json();}).then(function(d){var a=d.results||[];out.innerHTML=a.map(function(m){var poster=m.poster?'<img src=\\\"'+safe(m.poster)+'\\\" alt=\\\"'+safe(m.title)+' 포스터\\\">':'<div class=\\\"movie-poster-empty\\\">NO POSTER</div>';return '<a class=\\\"popular-movie-card\\\" href=\\\"/movies/'+m.id+'\\\">'+poster+'<span><b>'+safe(m.title)+'</b><small>'+safe(m.originalTitle)+'</small></span></a>';}).join('')||'<p class=\\\"muted\\\">표시할 영화가 없습니다.</p>';}).catch(function(){out.innerHTML='<p class=\\\"muted\\\">인기 영화를 불러오지 못했습니다.</p>';});}"
        +"function bindMovieSearch(){var q=document.getElementById('movieQuery'),s=document.getElementById('movieStatus'),out=document.getElementById('movieResults');function cards(a){out.innerHTML=a.map(function(m){var img=m.poster?'<img src=\\\"'+safe(m.poster)+'\\\" style=\\\"width:120px;height:170px;object-fit:cover;float:left;margin-right:18px\\\">':'';var reason=m.reason?'<p class=\\\"movie-reason\\\"><b>AI 추천 이유</b> '+safe(m.reason)+'</p>':'';return '<article class=\\\"post-card movie-card\\\" style=\\\"cursor:pointer\\\" onclick=\\\"location.href=\\\'/movies/'+m.id+'\\\'\\\">'+img+'<h3>'+safe(m.title)+'</h3><p class=\\\"muted\\\">'+safe(m.originalTitle)+'</p><p>'+safe(m.overview)+'</p>'+reason+'<div style=\\\"clear:both\\\"></div></article>';}).join('');}function search(){var v=q.value.trim();if(!v)return;s.textContent='AI가 요청을 분석해 영화를 찾는 중입니다.';fetch('/api/movies/search?q='+encodeURIComponent(v)).then(function(r){return r.json();}).then(function(d){var a=d.results||[];s.textContent=a.length?'AI 추천 결과 '+a.length+'편':'영화 데이터에 결과가 없습니다.';cards(a);}).catch(function(){s.textContent='영화 검색에 실패했습니다.';});}document.getElementById('movieSearchButton').onclick=search;document.getElementById('movieRandomButton').onclick=function(){s.textContent='AI가 오늘의 한 편을 고르는 중입니다.';fetch('/api/movies/random').then(function(r){return r.json();}).then(function(d){if(d.error){s.textContent=d.error;return;}var a=d.results||[];if(!a.length){s.textContent='추천할 영화를 찾지 못했습니다.';return;}s.textContent='AI 랜덤 추천';cards([a[0]]);});};q.addEventListener('keydown',function(e){if(e.key==='Enter')search();});}"
        +";function loadMovieDetail(id){fetch('/api/movies/'+id).then(function(r){if(!r.ok)throw 0;return r.json();}).then(function(m){var img=m.poster?'<img class=\\\"movie-detail-poster\\\" src=\\\"'+safe(m.poster)+'\\\" alt=\\\"'+safe(m.title)+'\\\">':'';document.getElementById('movieDetail').innerHTML='<a class=\\\"muted\\\" href=\\\"/movies\\\">← 영화 검색으로</a><article class=\\\"movie-detail-card\\\">'+img+'<div><span class=\\\"muted\\\">MOVIE DETAIL</span><h1>'+safe(m.title)+'</h1><p class=\\\"muted\\\">'+safe(m.originalTitle)+'</p><hr><p>'+safe(m.overview)+'</p></div></article>';}).catch(function(){document.getElementById('movieDetail').innerHTML='<p>영화 정보를 찾을 수 없습니다.</p>';});}"
        +"function loadNotifications(){fetch('/api/notifications').then(function(r){return r.json();}).then(function(d){document.getElementById('notifications').innerHTML=(d.notifications||[]).map(function(n){return '<a class=\\\"post-card\\\" href=\\\"'+safe(n.link||'#')+'\\\"><b>'+safe(n.type)+'</b><p>'+safe(n.message)+'</p><small class=\\\"muted\\\">'+(n.read?'읽음':'새 알림')+'</small></a>';}).join('')||'<p class=\\\"muted\\\">새 알림이 없습니다.</p>';return fetch('/api/notifications/read',{method:'PUT'});});}"
        +"function sessionNav(){fetch('/api/me').then(function(r){return r.ok?r.json():null;}).then(function(u){if(!u)return;document.getElementById('navLogin').style.display='none';document.getElementById('navRegister').style.display='none';document.getElementById('navUser').style.display='inline-block';document.getElementById('navLogout').style.display='inline-block';document.getElementById('navNotifications').style.display='list-item';document.getElementById('navMyPage').textContent=u.nickname+'님';if(u.role==='ADMIN')document.getElementById('navAdmin').style.display='list-item';});}"
        +"function loadAdmin(){fetch('/api/admin/stats').then(function(r){return r.json();}).then(function(s){document.getElementById('stats').textContent='게시글 '+s.posts+' · 댓글 '+s.comments+' · 회원 '+s.users+' · 미처리 신고 '+s.pendingReports;return fetch('/api/admin/users');}).then(function(r){return r.json();}).then(function(d){document.getElementById('users').innerHTML=(d.users||[]).map(function(u){var action=u.status==='SUSPENDED'?'ACTIVE':'SUSPENDED';return '<div class=\\\"post-card\\\"><b>'+safe(u.nickname)+'</b> ('+safe(u.loginId)+') · '+safe(u.status)+' <button class=\\\"btn-main\\\" onclick=\\\"setUserStatus('+u.id+',\\\''+action+'\\\')\\\">'+(action==='SUSPENDED'?'정지':'정지 해제')+'</button></div>';}).join('');}).catch(function(){location.href='/';});}function setUserStatus(id,status){fetch('/api/admin/users/'+id+'/status',{method:'PUT',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'status='+status}).then(function(){loadAdmin();});}function loadAdminPosts(){fetch('/api/posts').then(function(r){return r.json();}).then(function(d){document.getElementById('adminPosts').innerHTML=(d.posts||[]).map(function(p){return '<div class=\\\"post-card\\\"><b>'+safe(p.title)+'</b> · '+safe(p.author)+' <a class=\\\"btn-main\\\" href=\\\"/post/'+p.id+'\\\">보기</a> <button class=\\\"btn-main\\\" onclick=\\\"hidePost('+p.id+')\\\">숨김</button></div>';}).join('')||'<p class=\\\"muted\\\">표시할 게시글이 없습니다.</p>';});}function hidePost(id){if(!confirm('이 게시글을 숨길까요?'))return;fetch('/api/admin/posts/'+id+'/hide',{method:'PUT'}).then(function(r){if(r.ok){loadAdminPosts();loadAdmin();}});}"
        +"function loadReports(){fetch('/api/admin/reports').then(function(r){return r.json();}).then(function(d){document.getElementById('reports').innerHTML=(d.reports||[]).map(function(x){return '<div class=\\\"post-card\\\"><b>'+safe(x.type)+' #'+x.targetId+'</b> · '+safe(x.reason)+' · '+safe(x.status)+' <button class=\\\"btn-main\\\" onclick=\\\"resolveReport('+x.id+',\\\'RESOLVED\\\')\\\">처리</button> <button class=\\\"btn-main\\\" onclick=\\\"resolveReport('+x.id+',\\\'REJECTED\\\')\\\">반려</button></div>';}).join('')||'<p class=\\\"muted\\\">신고가 없습니다.</p>';});}function resolveReport(id,status){fetch('/api/admin/reports/'+id,{method:'PUT',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'status='+status}).then(function(){loadReports();loadAdmin();});}"
        +"function bindBoardForm(){document.getElementById('boardForm').addEventListener('submit',function(e){e.preventDefault();fetch('/api/boards',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(new FormData(e.target))}).then(function(r){if(r.ok){e.target.reset();loadBoards();}else document.getElementById('message').textContent='추가하지 못했습니다.';});});}function loadBoards(){fetch('/api/boards').then(function(r){return r.json();}).then(function(d){window.currentBoards=d.boards||[];document.getElementById('boards').innerHTML=window.currentBoards.map(function(b){return '<div class=\\\"post-card\\\"><b>'+safe(b.name)+'</b> · '+safe(b.description)+' <button class=\\\"btn-main\\\" onclick=\\\"editBoard('+b.id+')\\\">수정</button> <button class=\\\"btn-main\\\" onclick=\\\"removeBoard('+b.id+')\\\">삭제</button></div>';}).join('');});}function editBoard(id){var b=(window.currentBoards||[]).filter(function(x){return x.id===id;})[0];if(!b)return;var name=prompt('게시판 이름',b.name);if(name===null||!name.trim())return;var description=prompt('게시판 설명',b.description||'');if(description===null)return;fetch('/api/boards/'+id,{method:'PUT',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({name:name.trim(),description:description,sortOrder:99})}).then(function(r){if(r.ok)loadBoards();});}function removeBoard(id){if(!confirm('게시판을 삭제할까요?'))return;fetch('/api/boards/'+id,{method:'DELETE'}).then(function(r){if(r.ok)loadBoards();});}"
        +"function loadPostDetail(id){Promise.all([fetch('/api/posts/'+id).then(function(r){return r.json();}),fetch('/api/me').then(function(r){return r.ok?r.json():null;})]).then(function(a){var p=a[0],u=a[1],root=document.getElementById('post');root.innerHTML='<p class=\"muted\"></p><h1></h1><p class=\"post-stats\"></p><hr><div class=\"post-body\"></div><div id=\"postActions\"></div>';root.querySelector('p.muted').textContent=p.author+' · '+p.createdAt;root.querySelector('h1').textContent=p.title;root.querySelector('.post-body').textContent=p.content;var stats=root.querySelector('.post-stats');stats.textContent='조회 '+p.views+' · 좋아요 ';var count=document.createElement('b');count.id='likeCount';count.textContent=p.likes;stats.appendChild(count);if(u){var like=document.createElement('button');like.className='btn-main post-like-button';like.id='likeButton';like.textContent=p.liked?'♥ 좋아요 취소':'♡ 좋아요';like.onclick=function(){togglePostLike(id);};stats.appendChild(document.createTextNode(' '));stats.appendChild(like);}if(u&&(u.id===p.authorId||u.role==='ADMIN')){var actions=document.getElementById('postActions');actions.innerHTML='<p><a class=\"btn-main\" href=\"/edit-post/'+id+'\">수정</a> <button class=\"btn-main\" id=\"deletePostButton\">삭제</button></p>';document.getElementById('deletePostButton').onclick=function(){deletePost(id);};}}).catch(function(){document.getElementById('post').textContent='게시글을 찾을 수 없습니다.';});}function togglePostLike(id){fetch('/api/posts/'+id+'/like',{method:'POST'}).then(function(r){if(r.status===401){location.href='/login';return null;}return r.json();}).then(function(d){if(!d)return;document.getElementById('likeCount').textContent=d.likes;document.getElementById('likeButton').textContent=d.liked?'♥ 좋아요 취소':'♡ 좋아요';});}function logoutNow(){fetch('/api/auth/logout',{method:'POST'}).then(function(){location.href='/';});}function withdrawAccount(){if(!confirm('회원 탈퇴 후에는 같은 계정으로 다시 로그인할 수 없습니다. 계속할까요?'))return;fetch('/api/me',{method:'DELETE'}).then(function(r){if(r.ok){alert('회원 탈퇴가 완료되었습니다.');location.href='/';return;}return r.json();}).then(function(d){if(d)alert(d.error||'회원 탈퇴를 처리하지 못했습니다.');});}sessionNav();";
    private User session(HttpExchange e){String token=cookie(e);User cached=sessions.get(token);if(cached==null)throw new IllegalStateException("login required");User current=users.findByUserId(cached.getUserId());if(current==null||!"ACTIVE".equals(current.getStatus())){sessions.remove(token);csrfTokens.remove(token);throw new IllegalStateException("login required");}sessions.put(token,current);return current;} private boolean needsCsrf(HttpExchange e){String method=e.getRequestMethod();return ("POST".equals(method)||"PUT".equals(method)||"DELETE".equals(method))&&!cookie(e).isBlank()&&!"/api/auth/login".equals(e.getRequestURI().getPath())&&!"/api/auth/register".equals(e.getRequestURI().getPath());} private boolean csrfValid(HttpExchange e){String expected=csrfTokens.get(cookie(e));String actual=e.getRequestHeaders().getFirst("X-CSRF-Token");return expected!=null&&expected.equals(actual);} private static String cookie(HttpExchange e){String raw=e.getRequestHeaders().getFirst("Cookie");if(raw!=null)for(String part:raw.split(";")){String[] p=part.trim().split("=",2);if(p.length==2&&"CINEHUB_SESSION".equals(p[0]))return p[1];}return"";}
    private static Map<String,String> form(HttpExchange e)throws IOException{String body=new String(e.getRequestBody().readAllBytes(),StandardCharsets.UTF_8);Map<String,String> out=new HashMap<>();for(String item:body.split("&")){int n=item.indexOf('=');if(n>=0)out.put(URLDecoder.decode(item.substring(0,n),StandardCharsets.UTF_8),URLDecoder.decode(item.substring(n+1),StandardCharsets.UTF_8));}return out;} private static String req(Map<String,String> f,String key){String value=f.get(key);if(value==null||value.isBlank())throw new IllegalArgumentException(key+" is required");return value;} private static long id(String path){for(String part:path.split("/"))if(part.matches("\\d+"))return Long.parseLong(part);throw new IllegalArgumentException("id required");}
    private static String query(HttpExchange e,String key){String raw=e.getRequestURI().getRawQuery();if(raw!=null)for(String pair:raw.split("&")){String[] p=pair.split("=",2);if(p.length==2&&key.equals(p[0]))return URLDecoder.decode(p[1],StandardCharsets.UTF_8);}return "";}private static boolean get(HttpExchange e){return"GET".equals(e.getRequestMethod());}private static boolean post(HttpExchange e){return"POST".equals(e.getRequestMethod());}private static boolean put(HttpExchange e){return"PUT".equals(e.getRequestMethod());}private static boolean delete(HttpExchange e){return"DELETE".equals(e.getRequestMethod());}private static String esc(String s){return(s==null?"":s).replace("\\","\\\\").replace("\"","\\\"").replace("\n"," ").replace("\r"," ");}private static void json(HttpExchange e,int code,String body)throws IOException{send(e,code,"application/json; charset=utf-8",body);}private static void html(HttpExchange e,int code,String body)throws IOException{send(e,code,"text/html; charset=utf-8",addPostListStats(body));}private static String addPostListStats(String body){String script="<script>(function(){var timer;function fill(){fetch('/api/posts').then(function(r){return r.json();}).then(function(d){var by={};(d.posts||[]).forEach(function(p){by[p.id]=p;});document.querySelectorAll('a.post-card:not([data-list-stats])').forEach(function(card){var m=(card.getAttribute('href')||'').match(/\\/post\\/(\\d+)/);var p=m&&by[m[1]];if(!p)return;var s=document.createElement('small');s.className='muted post-list-stats';s.textContent='조회 '+p.views+' · 좋아요 '+p.likes;card.appendChild(s);card.setAttribute('data-list-stats','1');});});}function schedule(){clearTimeout(timer);timer=setTimeout(fill,40);}new MutationObserver(schedule).observe(document.documentElement,{childList:true,subtree:true});schedule();})();</script>";return body.replace("</body>",script+"</body>");}private static void redirect(HttpExchange e,String location)throws IOException{e.getResponseHeaders().set("Location",location);e.sendResponseHeaders(302,-1);e.close();}private static void send(HttpExchange e,int code,String type,String body)throws IOException{byte[] b=body.getBytes(StandardCharsets.UTF_8);e.getResponseHeaders().set("Content-Type",type);e.getResponseHeaders().set("Cache-Control","no-store");e.sendResponseHeaders(code,b.length);e.getResponseBody().write(b);e.close();}
}
