package project;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

/** Creates the supplied Oracle XE project account and applies miniproject.sql. */
public final class OracleSchemaSetup {
    public static void main(String[] args) throws Exception {
        String url = value("DB_URL", "jdbc:oracle:thin:@localhost:1521:XE");
        String appUser = value("DB_USER", "c##project");
        String appPassword = required("DB_PASSWORD");
        String adminUser = value("ORACLE_ADMIN_USER", "system");
        String adminPassword = required("ORACLE_ADMIN_PASSWORD");
        Class.forName("oracle.jdbc.OracleDriver");
        try (Connection admin = DriverManager.getConnection(url, adminUser, adminPassword); Statement s = admin.createStatement()) {
            if ("true".equalsIgnoreCase(value("ORACLE_RESET_SCHEMA", "false"))) {
                try { s.executeUpdate("DROP USER " + identifier(appUser) + " CASCADE"); }
                catch (SQLException missing) { if (missing.getErrorCode() != 1918) throw missing; }
            }
            try { s.executeUpdate("CREATE USER " + identifier(appUser) + " IDENTIFIED BY \"" + appPassword.replace("\"", "\"\"") + "\""); }
            catch (SQLException exists) { if (exists.getErrorCode() != 1920) throw exists; }
            s.executeUpdate("GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE TRIGGER, CREATE PROCEDURE, UNLIMITED TABLESPACE TO " + identifier(appUser));
        }
        String script = Files.readString(Path.of(args.length == 0 ? "webapp/db/miniproject.sql" : args[0]), StandardCharsets.UTF_8);
        script = script.replaceAll("(?m)^\\s*--.*$", "");
        try (Connection app = DriverManager.getConnection(url, appUser, appPassword); Statement s = app.createStatement()) {
            for (String statement : script.split(";")) {
                String sql = statement.trim();
                if (!sql.isBlank() && !sql.toUpperCase().startsWith("DESC ")) {
                    try { s.execute(sql); }
                    catch (SQLException alreadyExists) {
                        // Re-running setup must preserve the existing Oracle data/schema.
                        if (alreadyExists.getErrorCode() != 955 && alreadyExists.getErrorCode() != 4081 && alreadyExists.getErrorCode() != 2264) throw alreadyExists;
                    }
                }
            }
            s.execute("MERGE INTO boards b USING (SELECT '공지사항' name, '서비스 공지' description, 1 sort_order FROM dual) x ON (b.name=x.name) WHEN NOT MATCHED THEN INSERT (name,description,sort_order) VALUES (x.name,x.description,x.sort_order)");
            s.execute("MERGE INTO boards b USING (SELECT '자유게시판' name, '자유롭게 이야기하는 공간' description, 2 sort_order FROM dual) x ON (b.name=x.name) WHEN NOT MATCHED THEN INSERT (name,description,sort_order) VALUES (x.name,x.description,x.sort_order)");
            s.execute("MERGE INTO boards b USING (SELECT '영화 추천' name, '영화 추천과 감상' description, 3 sort_order FROM dual) x ON (b.name=x.name) WHEN NOT MATCHED THEN INSERT (name,description,sort_order) VALUES (x.name,x.description,x.sort_order)");
            try { s.execute("CREATE TABLE contact_messages (message_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, sender_name VARCHAR2(80) NOT NULL, email VARCHAR2(255) NOT NULL, message CLOB NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL)"); }
            catch (SQLException alreadyExists) { if (alreadyExists.getErrorCode() != 955) throw alreadyExists; }
            try { s.execute("CREATE TABLE notifications (notification_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id NUMBER NOT NULL, type VARCHAR2(30) NOT NULL, message VARCHAR2(500) NOT NULL, link VARCHAR2(255), is_read CHAR(1) DEFAULT 'N' NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT fk_notifications_user FOREIGN KEY(user_id) REFERENCES users(user_id) ON DELETE CASCADE)"); }
            catch (SQLException alreadyExists) { if (alreadyExists.getErrorCode() != 955) throw alreadyExists; }
        }
        System.out.println("Oracle schema applied for " + appUser + ".");
    }
    private static String identifier(String value) { if (!value.matches("[A-Za-z][A-Za-z0-9_$#]*")) throw new IllegalArgumentException("Invalid Oracle identifier"); return value; }
    private static String required(String key) { String value = value(key, ""); if (value.isBlank()) throw new IllegalArgumentException(key + " is required"); return value; }
    private static String value(String key, String fallback) { String v = System.getProperty(key); if (v != null && !v.isBlank()) return v; v = System.getenv(key); return v == null || v.isBlank() ? fallback : v; }
}
