# 7일차

## Oracle 시퀀스, 테이블 관리 및 제약조건

📌 학습일: 2026.07.28

📌 학습 내용: SEQUENCE, IDENTITY, CREATE TABLE AS SELECT, ALTER TABLE, RENAME, DROP, TRUNCATE, COMMENT, 데이터 사전, 무결성 제약조건

---

#### 1. SEQUENCE 생성

```sql
CREATE SEQUENCE 시퀀스명
START WITH 시작값
INCREMENT BY 증가값
MAXVALUE 최대값;
```

일련번호를 자동으로 생성하는 시퀀스를 생성한다.

#### 2. 시퀀스 정보 조회

```sql
SELECT SEQUENCE_NAME, MIN_VALUE, MAX_VALUE, INCREMENT_BY, LAST_NUMBER
FROM USER_SEQUENCES
WHERE SEQUENCE_NAME = '시퀀스명';
```

현재 사용자가 생성한 시퀀스의 최소값, 최대값, 증가값, 다음에 생성될 값을 조회한다.

#### 3. NEXTVAL로 다음 시퀀스 값 생성

```sql
SELECT 시퀀스명.NEXTVAL
FROM DUAL;
```

시퀀스의 다음 값을 생성하고 반환한다.

#### 4. CURRVAL로 현재 시퀀스 값 조회

```sql
SELECT 시퀀스명.CURRVAL
FROM DUAL;
```

현재 세션에서 마지막으로 생성한 시퀀스 값을 조회한다.

`CURRVAL`은 같은 세션에서 `NEXTVAL`을 한 번 이상 실행한 뒤 사용할 수 있다.

#### 5. 시퀀스를 이용한 데이터 입력

```sql
INSERT INTO 테이블명(번호컬럼, 컬럼명1, 컬럼명2)
VALUES(시퀀스명.NEXTVAL, 값1, 값2);
```

시퀀스의 다음 값을 번호 컬럼에 입력한다.

#### 6. 시퀀스 속성 변경

```sql
ALTER SEQUENCE 시퀀스명
MAXVALUE 변경할최대값;
```

생성된 시퀀스의 최대값 등의 속성을 변경한다.

#### 7. 시퀀스 삭제

```sql
DROP SEQUENCE 시퀀스명;
```

생성된 시퀀스를 삭제한다.

#### 8. IDENTITY를 이용한 자동 증가 컬럼 생성

```sql
CREATE TABLE 테이블명(
    번호컬럼 NUMBER GENERATED BY DEFAULT AS IDENTITY,
    일반컬럼 데이터형
);
```

번호 컬럼의 값을 입력하지 않아도 Oracle이 자동으로 번호를 생성한다.

#### 9. 기본 테이블 생성

```sql
CREATE TABLE 테이블명(
    컬럼명1 데이터형,
    컬럼명2 데이터형,
    컬럼명3 데이터형
);
```

지정한 컬럼과 데이터형으로 새로운 테이블을 생성한다.

#### 10. 기존 테이블의 전체 구조와 데이터 복사

```sql
CREATE TABLE 새테이블명
AS
SELECT *
FROM 기존테이블명;
```

기존 테이블의 모든 컬럼 구조와 데이터를 복사하여 새 테이블을 생성한다.

#### 11. 기존 테이블의 일부 컬럼과 데이터 복사

```sql
CREATE TABLE 새테이블명
AS
SELECT 복사할컬럼명1, 복사할컬럼명2
FROM 기존테이블명;
```

기존 테이블에서 선택한 컬럼의 구조와 데이터만 복사한다.

#### 12. 기존 테이블의 구조만 복사

```sql
CREATE TABLE 새테이블명
AS
SELECT 복사할컬럼명1, 복사할컬럼명2
FROM 기존테이블명
WHERE 1 = 2;
```

`WHERE 1 = 2`는 항상 거짓이므로 데이터는 복사되지 않고 선택한 컬럼의 구조만 복사된다.

#### 13. 테이블에 컬럼 추가

```sql
ALTER TABLE 테이블명
ADD (새컬럼명 데이터형);
```

기존 테이블에 새로운 컬럼을 추가한다.

#### 14. 기본값이 있는 컬럼 추가

```sql
ALTER TABLE 테이블명
ADD (새컬럼명 데이터형 DEFAULT 기본값);
```

새로운 컬럼을 추가하고 값이 입력되지 않았을 때 사용할 기본값을 지정한다.

#### 15. 테이블의 컬럼 삭제

```sql
ALTER TABLE 테이블명
DROP COLUMN 삭제할컬럼명;
```

기존 테이블에서 지정한 컬럼을 삭제한다.

#### 16. 컬럼의 데이터형 또는 크기 변경

```sql
ALTER TABLE 테이블명
MODIFY 변경할컬럼명 데이터형;
```

기존 컬럼의 데이터형이나 데이터 크기를 변경한다.

#### 17. 테이블 이름 변경

```sql
RENAME 기존테이블명 TO 새테이블명;
```

기존 테이블의 이름을 변경한다.

#### 18. 테이블 삭제

```sql
DROP TABLE 테이블명;
```

테이블의 구조와 저장된 데이터를 모두 삭제한다.

#### 19. 테이블의 전체 데이터 삭제

```sql
TRUNCATE TABLE 테이블명;
```

테이블의 구조는 유지하고 저장된 모든 데이터를 삭제한다.

`TRUNCATE`는 DDL이므로 `ROLLBACK`으로 복구할 수 없다.

#### 20. 테이블에 주석 추가

```sql
COMMENT ON TABLE 테이블명
IS '테이블 설명';
```

테이블의 용도나 설명을 주석으로 저장한다.

#### 21. 컬럼에 주석 추가

```sql
COMMENT ON COLUMN 테이블명.컬럼명
IS '컬럼 설명';
```

특정 컬럼의 의미나 용도를 주석으로 저장한다.

#### 22. 컬럼 주석 삭제

```sql
COMMENT ON COLUMN 테이블명.컬럼명
IS '';
```

컬럼에 등록된 주석을 삭제한다.

#### 23. 테이블 주석 조회

```sql
SELECT TABLE_NAME, COMMENTS
FROM USER_TAB_COMMENTS
WHERE TABLE_NAME = '조회할테이블명';
```

특정 테이블의 이름과 테이블 주석을 조회한다.

#### 24. 컬럼 주석 조회

```sql
SELECT TABLE_NAME, COLUMN_NAME, COMMENTS
FROM USER_COL_COMMENTS
WHERE TABLE_NAME = '조회할테이블명';
```

특정 테이블의 컬럼명과 컬럼 주석을 조회한다.

#### 25. 현재 사용자의 테이블 목록 조회

```sql
SELECT TABLE_NAME
FROM USER_TABLES;
```

현재 접속한 사용자가 소유한 모든 테이블 이름을 조회한다.

#### 26. 접근 가능한 전체 테이블 조회

```sql
SELECT OWNER, TABLE_NAME
FROM ALL_TABLES;
```

현재 사용자가 접근할 수 있는 테이블과 해당 테이블의 소유자를 조회한다.

#### 27. 데이터베이스의 전체 테이블 조회

```sql
SELECT OWNER, TABLE_NAME
FROM DBA_TABLES;
```

데이터베이스에 존재하는 모든 테이블과 소유자를 조회한다.

DBA 권한이 있는 계정에서 사용할 수 있다.

#### 28. 사용자 객체 정보 조회

```sql
SELECT OBJECT_NAME, OBJECT_TYPE, CREATED
FROM USER_OBJECTS
WHERE OBJECT_NAME LIKE '검색문자%';
```

현재 사용자가 소유한 객체의 이름, 종류, 생성일을 조회한다.

#### 29. 사용자 객체 목록 조회

```sql
SELECT TABLE_NAME, TABLE_TYPE
FROM USER_CATALOG;
```

현재 사용자가 소유한 테이블, 뷰, 시퀀스 등의 객체 목록을 조회한다.

#### 30. 특정 이름으로 시작하는 테이블 정보 조회

```sql
SELECT TABLE_NAME, TABLESPACE_NAME, MIN_EXTENTS, MAX_EXTENTS
FROM USER_TABLES
WHERE TABLE_NAME LIKE '검색문자%';
```

특정 문자로 시작하는 테이블과 테이블스페이스 정보를 조회한다.

#### 31. 테이블스페이스 생성

```sql
CREATE TABLESPACE 테이블스페이스명
DATAFILE '데이터파일경로'
SIZE 파일크기;
```

데이터베이스 객체를 저장할 새로운 테이블스페이스를 생성한다.

#### 32. PRIMARY KEY 제약조건 설정

```sql
CREATE TABLE 테이블명(
    컬럼명 데이터형
        CONSTRAINT 제약조건명 PRIMARY KEY
);
```

컬럼에 중복값과 `NULL`을 허용하지 않는 기본키를 설정한다.

#### 33. NOT NULL 제약조건 설정

```sql
CREATE TABLE 테이블명(
    컬럼명 데이터형
        CONSTRAINT 제약조건명 NOT NULL
);
```

해당 컬럼에 `NULL`이 입력되지 않도록 설정한다.

#### 34. CHECK 제약조건 설정

```sql
CREATE TABLE 테이블명(
    컬럼명 데이터형
        CONSTRAINT 제약조건명 CHECK (조건식)
);
```

지정한 조건을 만족하는 값만 입력할 수 있도록 제한한다.

#### 35. FOREIGN KEY 제약조건 설정

```sql
CREATE TABLE 자식테이블명(
    외래키컬럼 데이터형
        CONSTRAINT 제약조건명
        REFERENCES 부모테이블명(참조컬럼명)
);
```

자식 테이블의 컬럼이 부모 테이블의 기본키 또는 고유키를 참조하도록 설정한다.

#### 36. 복합 PRIMARY KEY 설정

```sql
CREATE TABLE 테이블명(
    컬럼명1 데이터형,
    컬럼명2 데이터형,
    CONSTRAINT 제약조건명 PRIMARY KEY(컬럼명1, 컬럼명2)
);
```

두 개 이상의 컬럼을 묶어 하나의 기본키로 설정한다.

#### 37. 기존 테이블에 UNIQUE 제약조건 추가

```sql
ALTER TABLE 테이블명
ADD CONSTRAINT 제약조건명
UNIQUE(컬럼명);
```

기존 테이블의 컬럼에 중복값을 허용하지 않는 고유키를 추가한다.

#### 38. 기존 테이블에 NOT NULL 제약조건 추가

```sql
ALTER TABLE 테이블명
MODIFY (
    컬럼명 CONSTRAINT 제약조건명 NOT NULL
);
```

기존 컬럼에 `NOT NULL` 제약조건을 추가한다.

#### 39. 기존 테이블에 PRIMARY KEY 추가

```sql
ALTER TABLE 테이블명
ADD CONSTRAINT 제약조건명
PRIMARY KEY(컬럼명);
```

기존 테이블의 컬럼에 기본키를 추가한다.

#### 40. 기존 테이블에 FOREIGN KEY 추가

```sql
ALTER TABLE 자식테이블명
ADD CONSTRAINT 제약조건명
FOREIGN KEY(외래키컬럼명)
REFERENCES 부모테이블명(참조컬럼명);
```

기존 자식 테이블의 컬럼이 부모 테이블의 컬럼을 참조하도록 설정한다.

#### 41. 제약조건 목록 조회

```sql
SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, STATUS
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = '조회할테이블명';
```

특정 테이블에 설정된 제약조건의 이름, 종류, 활성화 상태를 조회한다.

- `P` : PRIMARY KEY
- `R` : FOREIGN KEY
- `U` : UNIQUE
- `C` : CHECK 또는 NOT NULL

#### 42. 여러 테이블의 제약조건 조회

```sql
SELECT TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE, STATUS
FROM USER_CONSTRAINTS
WHERE TABLE_NAME IN ('테이블명1', '테이블명2');
```

여러 테이블에 설정된 제약조건을 한 번에 조회한다.

#### 43. 제약조건이 설정된 컬럼 조회

```sql
SELECT TABLE_NAME, COLUMN_NAME, CONSTRAINT_NAME
FROM USER_CONS_COLUMNS
WHERE TABLE_NAME = '조회할테이블명';
```

특정 테이블에서 각 제약조건이 어느 컬럼에 설정되어 있는지 조회한다.

#### 44. 여러 테이블의 제약조건 컬럼 조회

```sql
SELECT TABLE_NAME, COLUMN_NAME, CONSTRAINT_NAME
FROM USER_CONS_COLUMNS
WHERE TABLE_NAME IN ('테이블명1', '테이블명2');
```

여러 테이블에서 제약조건이 설정된 컬럼을 조회한다.

#### 45. 제약조건 삭제

```sql
ALTER TABLE 테이블명
DROP CONSTRAINT 제약조건명;
```

기존 테이블에 설정된 제약조건을 삭제한다.

#### 46. 제약조건 비활성화

```sql
ALTER TABLE 테이블명
DISABLE CONSTRAINT 제약조건명;
```

제약조건을 삭제하지 않고 일시적으로 작동하지 않도록 설정한다.

#### 47. 제약조건 활성화

```sql
ALTER TABLE 테이블명
ENABLE CONSTRAINT 제약조건명;
```

비활성화된 제약조건을 다시 활성화한다.

#### 48. CHECK 제약조건 위반

```sql
INSERT INTO 테이블명(컬럼명)
VALUES(조건에맞지않는값);
```

입력값이 `CHECK` 조건을 만족하지 않으면 오류가 발생한다.

#### 49. PRIMARY KEY 제약조건 위반

```sql
INSERT INTO 테이블명(기본키컬럼)
VALUES(이미존재하는값);
```

기본키에 이미 존재하는 값을 중복 입력하면 오류가 발생한다.

#### 50. FOREIGN KEY 제약조건 위반

```sql
INSERT INTO 자식테이블명(외래키컬럼)
VALUES(부모테이블에없는값);
```

부모 테이블에 존재하지 않는 값을 외래키 컬럼에 입력하면 오류가 발생한다.

#### 51. 시퀀스와 PRIMARY KEY를 이용한 자동 번호 입력

```sql
CREATE TABLE 테이블명(
    번호컬럼 NUMBER PRIMARY KEY,
    일반컬럼 데이터형
);

CREATE SEQUENCE 시퀀스명
START WITH 시작값
INCREMENT BY 증가값;

INSERT INTO 테이블명(번호컬럼, 일반컬럼)
VALUES(시퀀스명.NEXTVAL, 일반값);
```

시퀀스에서 생성한 번호를 기본키 컬럼에 자동으로 입력한다.
